package id.webabsensi.app;
import android.app.*;import android.content.*;import android.os.*;import org.json.*;import javax.net.ssl.HttpsURLConnection;import java.net.URL;import java.nio.charset.StandardCharsets;
/** Visible, opt-in notification service. No location collection. */
public class AttendanceWatch extends Service {
 private volatile boolean running;private Thread worker;
 public static void notify(Context c,int id,String title,String body){NotificationManager m=(NotificationManager)c.getSystemService(NOTIFICATION_SERVICE);m.createNotificationChannel(new NotificationChannel("attendance","Pengingat absen",NotificationManager.IMPORTANCE_HIGH));Intent i=new Intent(c,MainActivity.class);PendingIntent p=PendingIntent.getActivity(c,0,i,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);m.notify(id,new Notification.Builder(c,"attendance").setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle(title).setContentText(body).setContentIntent(p).setAutoCancel(true).build());}
 @Override public void onCreate(){super.onCreate();NotificationManager m=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);m.createNotificationChannel(new NotificationChannel("watch","Layanan pengingat absen",NotificationManager.IMPORTANCE_LOW));startForeground(1,new Notification.Builder(this,"watch").setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle("Pengingat absen aktif").setContentText("Menunggu sesi dosen; tidak mengambil lokasi.").setOngoing(true).build());running=true;worker=new Thread(()->{while(running){try{check();Thread.sleep(10000);}catch(InterruptedException ignored){break;}catch(Exception ignored){try{Thread.sleep(10000);}catch(InterruptedException e){break;}}}},"attendance-reminders");worker.start();}
 private void check()throws Exception{android.content.SharedPreferences pref=getSharedPreferences("attendance",MODE_PRIVATE);String token=pref.getString("token","");if(token.isEmpty())return;HttpsURLConnection c=(HttpsURLConnection)new URL("https://"+BuildConfig.APP_HOST+"/app_api.php").openConnection();c.setRequestMethod("POST");c.setConnectTimeout(7000);c.setReadTimeout(7000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("X-App-Request","1");c.setRequestProperty("Authorization","Bearer "+token);c.setRequestProperty("Cookie",pref.getString("cookies",""));try{c.getOutputStream().write("{\"action\":\"snapshot\"}".getBytes(StandardCharsets.UTF_8));if(c.getResponseCode()==401){stopSelf();return;}if(c.getResponseCode()!=200)return;java.io.ByteArrayOutputStream bytes=new java.io.ByteArrayOutputStream();byte[] buffer=new byte[8192];try(java.io.InputStream in=c.getInputStream()){int read;while((read=in.read(buffer))!=-1){if(bytes.size()>4000000)return;bytes.write(buffer,0,read);}}String raw=new String(bytes.toByteArray(),StandardCharsets.UTF_8);JSONObject snapshot=new JSONObject(raw).getJSONObject("snapshot");JSONArray sessions=snapshot.getJSONArray("sessions"),marks=snapshot.getJSONArray("marks");long now=System.currentTimeMillis();for(int i=0;i<sessions.length();i++){JSONObject s=sessions.getJSONObject(i);String id=s.getString("id");boolean accepted=false;for(int j=0;j<marks.length();j++)if(id.equals(marks.getJSONObject(j).optString("session_id"))){accepted=true;break;}int notificationId=Math.abs(id.hashCode());if(accepted||now>s.getLong("deadline")){((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).cancel(notificationId);continue;}String phase=s.getLong("deadline")-now<=60000?"reminder":"start",key=id+"-"+s.getInt("version")+"-"+phase;if(pref.getBoolean(key,false))continue;notify(this,notificationId,"Absen mahasiswa",s.getString("matkul")+(phase.equals("start")?": absen dimulai. Pindai QR dosen.":": segera absen, kurang dari 1 menit tersisa."));pref.edit().putBoolean(key,true).apply();}}finally{c.disconnect();}}
 @Override public int onStartCommand(Intent i,int f,int id){return START_STICKY;}
 @Override public IBinder onBind(Intent i){return null;}
 @Override public void onTimeout(int id,int type){stopSelf();}
 @Override public void onDestroy(){running=false;if(worker!=null)worker.interrupt();super.onDestroy();}
}
