package id.webabsensi.app;
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.webkit.*;import android.print.*;import android.util.Base64;import android.widget.Toast;import java.io.*;import java.util.*;
public class MainActivity extends Activity {
 private WebView web;private ValueCallback<Uri[]> chooser;private PermissionRequest camera;private GeolocationPermissions.Callback geo;private String geoOrigin;private byte[] pendingFile;private String pendingName;private final String host=BuildConfig.APP_HOST;private volatile boolean bundleFallback;
 @Override public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);setContentView(web);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setGeolocationEnabled(true);s.setMediaPlaybackRequiresUserGesture(true);s.setAllowFileAccess(false);s.setAllowContentAccess(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);CookieManager.getInstance().setAcceptCookie(true);web.addJavascriptInterface(new Bridge(),"Android");web.setWebViewClient(new WebViewClient(){
  @Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();if("https".equals(u.getScheme())&&host.equals(u.getHost())){if(BuildConfig.APP_ROLE.equals("student")&&!studentPage(u)){Toast.makeText(MainActivity.this,"Aplikasi ini khusus absensi mahasiswa.",Toast.LENGTH_SHORT).show();return true;}return false;}if(Arrays.asList("https","http","mailto").contains(u.getScheme())){try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception ignored){} }return true;}
  @Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){if(!"GET".equals(r.getMethod())||!host.equals(r.getUrl().getHost())||online()&&!bundleFallback)return null;return offline(r.getUrl());}
  @Override public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError error){if(r.isForMainFrame())loadBundledPage(r.getUrl());}
  @Override public void onReceivedHttpError(WebView v,WebResourceRequest r,WebResourceResponse response){if(r.isForMainFrame()&&(response.getStatusCode()>=500||response.getStatusCode()==404))loadBundledPage(r.getUrl());}
 });web.setWebChromeClient(new WebChromeClient(){
  @Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams p){if(chooser!=null)chooser.onReceiveValue(null);chooser=cb;try{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);String[] types=p.getAcceptTypes();i.setType(types.length==1&&types[0].equals("image/*")?"image/*":"*/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,p.getMode()==FileChooserParams.MODE_OPEN_MULTIPLE);startActivityForResult(i,11);return true;}catch(Exception e){chooser=null;cb.onReceiveValue(null);return false;}}
  @Override public void onPermissionRequest(PermissionRequest p){runOnUiThread(()->{if(!host.equals(Uri.parse(p.getOrigin().toString()).getHost())){p.deny();return;}camera=p;if(checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED){p.grant(new String[]{PermissionRequest.RESOURCE_VIDEO_CAPTURE});camera=null;}else requestPermissions(new String[]{Manifest.permission.CAMERA},12);});}
  @Override public void onGeolocationPermissionsShowPrompt(String origin,GeolocationPermissions.Callback cb){geo=cb;geoOrigin=origin;if(!host.equals(Uri.parse(origin).getHost())){cb.invoke(origin,false,false);geo=null;return;}if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED){cb.invoke(origin,true,false);geo=null;}else requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},13);}
 });web.setDownloadListener((url,ua,cd,mime,length)->{if(url.startsWith("data:"))new Bridge().saveFile("dokumen",mime,url);else if(url.startsWith("blob:")){String js="fetch("+org.json.JSONObject.quote(url)+").then(r=>r.blob()).then(b=>{let x=new FileReader();x.onload=()=>Android.saveFile('dokumen',b.type,x.result);x.readAsDataURL(b);})";web.evaluateJavascript(js,null);}else if(url.startsWith("https://"+host+"/")){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception ignored){}}});if(b!=null)web.restoreState(b);else web.loadUrl("https://"+host+(BuildConfig.APP_ROLE.equals("teacher")?"/index.php":"/app/?role=student"));}
 private boolean studentPage(Uri u){String path=u.getPath();return path.equals("/app")||path.equals("/app/")||path.equals("/app/index.html");}
 private boolean online(){android.net.ConnectivityManager cm=(android.net.ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);android.net.NetworkCapabilities cap=cm.getNetworkCapabilities(cm.getActiveNetwork());return cap!=null&&cap.hasCapability(android.net.NetworkCapabilities.NET_CAPABILITY_VALIDATED);}
 private void loadBundledPage(Uri url){if(!host.equals(url.getHost()))return;WebResourceResponse response=offline(url);if(response==null||!"text/html".equals(response.getMimeType()))return;try(InputStream in=response.getData();ByteArrayOutputStream bytes=new ByteArrayOutputStream()){byte[] block=new byte[8192];int count;while((count=in.read(block))!=-1)bytes.write(block,0,count);String html=bytes.toString("UTF-8");bundleFallback=true;runOnUiThread(()->web.loadDataWithBaseURL(url.toString(),html,"text/html","UTF-8",url.toString()));}catch(IOException ignored){}}
 private WebResourceResponse offline(Uri u){try{String path=u.getPath().replaceFirst("^/","");if(path.equals("app")||path.equals("app/"))path="app/index.html";if(path.matches("(?:index|absen|ujian|data_siswa|music_player)\\.php"))path="app/templates/"+path.replace(".php",".html");if(path.contains("..")||!(path.startsWith("app/")||path.startsWith("assets/")||path.equals("app-sw.js")))return null;String ext=path.substring(path.lastIndexOf('.')+1);String mime=ext.equals("html")?"text/html":ext.equals("js")||ext.equals("mjs")?"application/javascript":ext.equals("css")?"text/css":ext.equals("json")?"application/json":ext.equals("wasm")?"application/wasm":ext.equals("svg")?"image/svg+xml":"application/octet-stream";return new WebResourceResponse(mime,"UTF-8",getAssets().open(path));}catch(Exception e){return null;}}
 @Override protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);web.saveState(b);}
 @Override public void onBackPressed(){web.evaluateJavascript("(async()=>{const d=document.querySelector('dialog[open]');if(d){d.close();return;}try{await window.WAFlush?.();Android.finishBack();}catch(e){alert('Perubahan disimpan di perangkat. Tunggu penyimpanan selesai sebelum kembali.');}})()",null);}

 @Override public void onRequestPermissionsResult(int request,String[] perms,int[] results){super.onRequestPermissionsResult(request,perms,results);boolean allowed=results.length>0&&results[0]==PackageManager.PERMISSION_GRANTED;if(request==12&&camera!=null){if(allowed)camera.grant(new String[]{PermissionRequest.RESOURCE_VIDEO_CAPTURE});else camera.deny();camera=null;}if(request==13&&geo!=null){geo.invoke(geoOrigin,allowed||results.length>1&&results[1]==PackageManager.PERMISSION_GRANTED,false);geo=null;}}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==11&&chooser!=null){Uri[] values=null;if(result==RESULT_OK&&data!=null){if(data.getClipData()!=null){values=new Uri[data.getClipData().getItemCount()];for(int i=0;i<values.length;i++)values[i]=data.getClipData().getItemAt(i).getUri();}else if(data.getData()!=null)values=new Uri[]{data.getData()};}chooser.onReceiveValue(values);chooser=null;}if(request==14&&pendingFile!=null){if(result==RESULT_OK&&data!=null){try(OutputStream out=getContentResolver().openOutputStream(data.getData())){out.write(pendingFile);Toast.makeText(this,"Berkas disimpan",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Berkas belum dapat disimpan",Toast.LENGTH_LONG).show();}}pendingFile=null;}}
 public class Bridge {
  @JavascriptInterface public void finishBack(){runOnUiThread(()->{if(web.canGoBack())web.goBack();else MainActivity.super.onBackPressed();});}
  @JavascriptInterface public String appRole(){return BuildConfig.APP_ROLE;}
  @JavascriptInterface public void printDocument(String html,String base){if(html==null||html.length()>20000000)return;runOnUiThread(()->{WebView printer=new WebView(MainActivity.this);printer.getSettings().setJavaScriptEnabled(false);printer.setWebViewClient(new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){return !online()||bundleFallback?offline(r.getUrl()):null;}@Override public void onPageFinished(WebView v,String url){printer.postDelayed(()->{PrintManager manager=(PrintManager)getSystemService(PRINT_SERVICE);manager.print("Lembar Absensi",printer.createPrintDocumentAdapter("Lembar Absensi"),new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).build());},500);}});printer.loadDataWithBaseURL("https://"+host+"/",html,"text/html","UTF-8",null);});}

  @JavascriptInterface public void print(){runOnUiThread(()->{PrintManager manager=(PrintManager)getSystemService(PRINT_SERVICE);manager.print("Lembar Absensi",web.createPrintDocumentAdapter("Lembar Absensi"),new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).build());});}
  @JavascriptInterface public void saveFile(String name,String mime,String data){if(data==null||data.length()>75000000||!data.matches("^(?:data:[^,]*;base64,)?[A-Za-z0-9+/=\\r\\n]+$"))return;try{byte[] bytes=Base64.decode(data.startsWith("data:")?data.substring(data.indexOf(',')+1):data,Base64.DEFAULT);runOnUiThread(()->{pendingFile=bytes;pendingName=name.replaceAll("[^\\p{L}\\p{N}_. -]","_");Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime==null||mime.isEmpty()?"application/octet-stream":mime);i.putExtra(Intent.EXTRA_TITLE,pendingName);startActivityForResult(i,14);});}catch(Exception ignored){}}
  @JavascriptInterface public void requestNotifications(){runOnUiThread(()->{if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},15);});}
  @JavascriptInterface public void notifySession(String id,String title,String body){AttendanceWatch.notify(MainActivity.this,Math.abs(id.hashCode()),title,body);}
  @JavascriptInterface public void notify(String title,String body){AttendanceWatch.notify(MainActivity.this,Math.abs(body.hashCode()),title,body);}
  @JavascriptInterface public void startWatch(String token,String nim){if(!BuildConfig.APP_ROLE.equals("student")||!token.matches("[a-f0-9]{64}"))return;String cookies=CookieManager.getInstance().getCookie("https://"+host+"/");getSharedPreferences("attendance",MODE_PRIVATE).edit().putString("token",token).putString("nim",nim).putString("cookies",cookies==null?"":cookies).apply();runOnUiThread(()->startForegroundService(new Intent(MainActivity.this,AttendanceWatch.class)));}
  @JavascriptInterface public void stopWatch(){stopService(new Intent(MainActivity.this,AttendanceWatch.class));getSharedPreferences("attendance",MODE_PRIVATE).edit().clear().apply();}
  @JavascriptInterface public void attendanceAccepted(String id){((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).cancel(Math.abs(id.hashCode()));}
 }
}
