const {app,BrowserWindow,session,net,protocol,ipcMain,dialog}=require('electron');const fs=require('node:fs'),path=require('node:path');
const HOST='datasiswasekolah.42web.io',ROOT=path.resolve(__dirname,'../..');let main;
function asset(url){const u=new URL(url);if(u.hostname!==HOST)return null;let rel=decodeURIComponent(u.pathname).replace(/^\//,'');if(rel==='app'||rel==='app/')rel='app/index.html';if(/^(index|data_siswa|absen|ujian|music_player)\.php$/.test(rel))rel='app/templates/'+rel.replace('.php','.html');if(!(rel.startsWith('app/')||rel.startsWith('assets/')||rel==='app-sw.js'))return null;const file=path.resolve(ROOT,rel);if(!file.startsWith(ROOT+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile())return null;const ext=path.extname(file),mime={'.html':'text/html; charset=utf-8','.js':'application/javascript','.mjs':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.wasm':'application/wasm','.png':'image/png','.webmanifest':'application/manifest+json'}[ext]||'application/octet-stream';return new Response(fs.readFileSync(file),{headers:{'Content-Type':mime}});}
function trusted(event){try{return new URL(event.senderFrame.url).hostname===HOST;}catch(_){return false;}}
app.whenReady().then(async()=>{
 protocol.handle('https',async request=>{try{return await net.fetch(request,{bypassCustomProtocolHandlers:true});}catch(e){const fallback=asset(request.url);if(fallback)return fallback;throw e;}});
 main=new BrowserWindow({width:1250,height:900,minWidth:600,minHeight:500,title:'Absensi Dosen',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});
 main.webContents.setWindowOpenHandler(({url})=>{if(new URL(url).hostname===HOST){main.loadURL(url);return {action:'deny'};}if(url.startsWith('https://'))require('electron').shell.openExternal(url);return {action:'deny'};});
 main.webContents.on('will-navigate',(event,url)=>{if(new URL(url).hostname!==HOST){event.preventDefault();if(url.startsWith('https://'))require('electron').shell.openExternal(url);}});
 session.defaultSession.setPermissionRequestHandler((wc,permission,callback,details)=>{const origin=details.requestingUrl||wc.getURL();if(!origin.startsWith('https://'+HOST+'/')||!['media','geolocation','notifications','clipboard-sanitized-write'].includes(permission)){callback(false);return;}dialog.showMessageBox(main,{type:'question',buttons:['Izinkan','Batal'],defaultId:1,title:'Izin aplikasi',message:permission==='media'?'Izinkan kamera untuk memindai QR?':permission==='geolocation'?'Izinkan lokasi untuk keterangan absen?':'Izinkan pemberitahuan absen?'}).then(x=>callback(x.response===0));});
 session.defaultSession.on('will-download',(event,item)=>{const name=path.basename(item.getFilename());const file=dialog.showSaveDialogSync(main,{defaultPath:name});if(file)item.setSavePath(file);else item.cancel();});
 ipcMain.handle('save-file',async(event,{name,mime,data})=>{if(!trusted(event)||typeof data!=='string'||data.length>75000000||!/^data:[^,]*;base64,/.test(data))return false;const result=await dialog.showSaveDialog(main,{defaultPath:path.basename(name||'dokumen')});if(result.canceled)return false;fs.writeFileSync(result.filePath,Buffer.from(data.slice(data.indexOf(',')+1),'base64'));return true;});
 ipcMain.handle('print-document',async(event,{html,base})=>{if(!trusted(event)||typeof html!=='string'||html.length>20000000)return false;const win=new BrowserWindow({show:false,webPreferences:{javascript:false,nodeIntegration:false,contextIsolation:true,sandbox:true}});const safeBase='https://'+HOST+'/';await win.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent(html.replace('<head>','<head><base href="'+safeBase+'">')));win.webContents.print({printBackground:true},()=>win.destroy());return true;});
 await main.loadURL('https://'+HOST+'/app/?role=teacher');
});
app.on('window-all-closed',()=>app.quit());
