'use strict';
const BUILD='20261010-reliable-4',PUBLIC='wa-public-'+BUILD,PRIVATE='wa-private-'+BUILD;
const root=new URL('./',self.location),url=path=>new URL(path,root).href;
const staticFiles=['app/','app/index.html','app/core.js','app/qr-files.js','app/app.js','app/app.css','app/icon.svg','app/icon-192.png','app/icon-512.png','app/manifest.webmanifest','assets/teacher-tools.js','assets/teacher-tools.css','assets/app-audio.js','assets/sheet-signatures.css','assets/sheet-signatures.js','assets/sheet-spacing.js','assets/offline-bridge.js','assets/native-export.js','app/templates/index.html','app/templates/data_siswa.html','app/templates/absen.html','app/templates/ujian.html','app/templates/music_player.html'];
async function state(){return new Promise(resolve=>{const r=indexedDB.open('web-absensi-offline',1);r.onupgradeneeded=()=>r.result.createObjectStore('records');r.onsuccess=()=>{const d=r.result,q=d.transaction('records').objectStore('records').get('state');q.onsuccess=()=>{resolve(q.result);d.close();};q.onerror=()=>resolve(null);};r.onerror=()=>resolve(null);});}
async function tell(data){for(const client of await self.clients.matchAll({includeUncontrolled:true}))client.postMessage(data);}
let preparing;
async function prepare(role='teacher',bundled=false){if(preparing)return preparing;return preparing=(async()=>{const c=await caches.open(PUBLIC),manifest=role==='student'||bundled?[]:await fetch(url('app/vendor-manifest.json'),{cache:'no-cache'}).then(r=>r.json()),paths=[...(role==='student'?staticFiles.filter(x=>!x.includes('templates/')&&!x.startsWith('assets/')):staticFiles),...manifest.map(x=>x.path),'app/vendor/qr.js','app/vendor/scan.js'];let next=0;await Promise.all(Array.from({length:6},async()=>{while(next<paths.length){const path=paths[next++],request=url(path),found=await c.match(request);if(found)continue;const r=await fetch(request,{cache:'no-cache'});if(!r.ok)throw Error(path);await c.put(request,r);await tell({type:'offline-progress',done:next,total:paths.length});}}));await c.put(url('app/offline-ready'+(role==='student'?'-student':'')),new Response(BUILD));await tell({type:'offline-ready',role});})().finally(()=>{preparing=null;});}
self.addEventListener('install',e=>e.waitUntil((async()=>{const c=await caches.open(PUBLIC);await c.addAll(['app/','app/index.html','app/core.js','app/qr-files.js','app/app.js','app/app.css','app/vendor/qr.js','app/vendor/scan.js','app/icon.svg']);})()));
// Activate on the next opening; an update never reloads a sheet while it is being edited.
self.addEventListener('activate',e=>e.waitUntil((async()=>{await self.clients.claim();for(const name of await caches.keys())if(name.startsWith('wa-public-')&&name!==PUBLIC)await caches.delete(name);})()));
self.addEventListener('message',e=>{if(e.data?.type==='prepare')e.waitUntil(prepare(e.data.role,e.data.bundled).catch(()=>tell({type:'offline-error'})));});
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(u.origin!==root.origin||e.request.method!=='GET')return;
const rel=u.pathname.slice(root.pathname.length),page=rel.match(/^(index|data_siswa|absen|ujian|music_player)\.php$/)?.[1];
if(page&&e.request.mode==='navigate'){e.respondWith((async()=>{try{const r=await fetch(e.request);if(r.ok){const s=await state();if(s?.profile?.role==='teacher'){const cache=await caches.open(PRIVATE);await cache.put(e.request,r.clone());}}return r;}catch(_){const s=await state();if(s?.profile?.role!=='teacher'){const login=await caches.match(url('app/templates/index.html'));if(login)return new Response(await login.text(),{headers:{'Content-Type':'text/html; charset=utf-8'}});return new Response('Masuk pertama kali memerlukan internet.',{status:503});}const saved=await caches.match(e.request);if(saved)return saved;const template=await caches.match(url('app/templates/'+page+'.html'));if(template)return new Response(await template.text(),{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});return new Response('Lembar offline belum diunduh. Buka aplikasi saat online untuk menyiapkannya.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});}})());return;}
if(rel.startsWith('app/')||rel.startsWith('assets/')){e.respondWith((async()=>{const c=await caches.open(PUBLIC),saved=await c.match(e.request,{ignoreSearch:true});if(saved)return saved;const r=await fetch(e.request);if(r.ok)await c.put(e.request,r.clone());return r;})());}
});
self.addEventListener('push',e=>{let data;try{data=e.data.json();}catch(_){return;}e.waitUntil(self.registration.showNotification(data.title||'Absen mahasiswa',{body:data.body||'',tag:data.tag||'wa-session',data:{url:url('app/?role=student')},icon:url('app/icon.svg')}));});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil((async()=>{const clients=await self.clients.matchAll({type:'window'});for(const c of clients)if(c.url.startsWith(root.href)){await c.focus();c.postMessage({type:'refresh-attendance'});return;}await self.clients.openWindow(e.notification.data?.url||url('app/?role=student'));})());});
