const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.WA_PLAYWRIGHT_PATH||'/workspace/cloud-web-absensi/browser-tools/node_modules/playwright-core');
const BASE=process.env.WA_TEST_URL||'http://127.0.0.1:8000/';if(!['127.0.0.1','localhost'].includes(new URL(BASE).hostname))throw Error('Tests only create fixtures on the local development server.');
async function waitFor(p,fn,arg,timeout=30000){const until=Date.now()+timeout;while(Date.now()<until){try{if(await p.evaluate(fn,arg))return;}catch(e){if(!/context was destroyed|detached|navigation/.test(e.message))throw e;}await p.waitForTimeout(100);}throw Error('Expected state not reached before '+timeout+' ms');}
const ROOT=path.resolve(__dirname,'..');
test('teacher approval, QR boundaries, offline receipts, persistence, sync, sheets and logout',{timeout:150000},async(t)=>{
 const browser=await chromium.launch({executablePath:process.env.WA_CHROMIUM||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const teacher=await browser.newContext(),student=await browser.newContext();const page=await teacher.newPage(),sp=await student.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));sp.on('pageerror',e=>errors.push(e.message));const suffix=Date.now(),course='QA-'+suffix;
 async function drained(p){await p.evaluate(()=>WA.sync());await waitFor(p,async()=>!(await WA.get()).outbox.length,null,20000);}
 try{
 await page.goto(BASE+'app/');await page.waitForSelector('#login');const source=fs.readFileSync(path.join(ROOT,'index.php'),'utf8'),user=source.match(/\$user === '([^']+)'/)[1],password=source.match(/\$pass === '([^']+)'/)[1];await page.locator('[name=username]').fill(user);await page.locator('[name=password]').fill(password);await page.locator('#login button').click();await page.waitForSelector('#sessionForm');
 const ctx={jenjang:'S1',prodi:'Pendidikan Teknologi Informasi',semester:'1',kelas:'A'},fixture={...ctx,nim:'QAC'+suffix,nama:'Mahasiswa pengujian',jk:'L'};await page.evaluate(async row=>WA.queue({type:'student-upsert',ctx:row,...row}),fixture);await drained(page);
 await sp.goto(BASE+'app/?role=student');await sp.waitForFunction(()=>!!window.WA);await sp.evaluate(async row=>WA.login('student',{register:true,...row,pin:'654321',ctx:row}),fixture);
 await t.test('new registration is pending and cannot submit teacher operations',async()=>{const s=await sp.evaluate(()=>WA.get());assert.equal(s.profile.account.approved,false);const r=await sp.evaluate(()=>WA.api('sync',{operations:[{id:crypto.randomUUID(),type:'approve',account:crypto.randomUUID()}]}));assert.equal(r.results[0].status,'error');assert.equal(r.snapshot.roster.length,0);assert.equal(r.snapshot.documents.length,0);});
 await page.evaluate(()=>WA.sync());const account=(await page.evaluate(()=>WA.get())).snapshot.registrations.find(x=>x.nim===fixture.nim);await page.evaluate(id=>WA.queue({type:'approve',account:id}),account.id);await drained(page);await sp.evaluate(()=>WA.sync());assert.equal((await sp.evaluate(()=>WA.get())).profile.account.approved,true);
 let session=await page.evaluate(async({ctx,course})=>WA.startSession(ctx,course,1,10),{ctx,course});await drained(page);let code=await page.evaluate(async x=>WA.qr('session',(await WA.get()).profile.certificate,'challenge',x.challenge),session);
 await t.test('class tampering is rejected',async()=>{await assert.rejects(()=>sp.evaluate(async code=>{const w=WA.decode(code.slice(4));const [body,sig]=w.challenge.split('.'),data=WA.decode(body);data.ctx.kelas='B';w.challenge=WA.encode(data)+'.'+sig;return WA.readQR('WA1:'+WA.encode(w));},code));});
 const reply=await sp.evaluate(async code=>WA.reply((await WA.readQR(code)).challenge,'.','',null),code);session=await page.evaluate(async({ctx,course})=>WA.startSession(ctx,course,1,10),{ctx,course});await drained(page);
 await t.test('reset invalidates old replies',async()=>{await assert.rejects(()=>sp.evaluate(code=>WA.submitReply(code),reply),/reset|terbaru/);});
 code=await page.evaluate(async x=>WA.qr('session',(await WA.get()).profile.certificate,'challenge',x.challenge),session);await student.setOffline(true);await teacher.setOffline(true);
 await t.test('both devices can complete attendance with no internet',async()=>{const r=await sp.evaluate(async code=>WA.reply((await WA.readQR(code)).challenge,'S','Sakit, sedang istirahat',null),code);await page.evaluate(code=>WA.receive(code),r);const s=await page.evaluate(()=>WA.get());assert.equal(s.snapshot.marks.find(m=>m.session_id===session.id&&m.nim===fixture.nim).mark,'S');assert(s.outbox.some(o=>o.type==='reply'));await page.reload();await page.waitForSelector('#sessionForm');assert.equal((await page.evaluate(()=>WA.get())).profile.role,'teacher');});
 await teacher.setOffline(false);await student.setOffline(false);await drained(page);await sp.evaluate(()=>WA.sync());
 await t.test('pending offline receipt syncs once and retains sick status',async()=>{const s=await page.evaluate(()=>WA.get()),mark=s.snapshot.marks.find(m=>m.session_id===session.id&&m.nim===fixture.nim);assert.equal(mark.mark,'S');assert.equal(mark.review_status,'pending');const count=s.snapshot.marks.filter(m=>m.session_id===session.id&&m.nim===fixture.nim).length;await page.evaluate(()=>WA.sync());assert.equal((await page.evaluate(()=>WA.get())).snapshot.marks.filter(m=>m.session_id===session.id&&m.nim===fixture.nim).length,count);});
 await t.test('expired session inserts A and rejects attendance after deadline',async()=>{await page.evaluate(async({ctx,course})=>{const s=await WA.get(),at=Date.now()-120000,x={v:1,type:'session',device:s.profile.device,id:crypto.randomUUID(),ctx,matkul:course,slot:2,starts:at,deadline:at+60000,ends:at+60000,version:1,nonce:'ab'.repeat(24)},challenge=await WA.seal(x);await WA.queue({type:'session',challenge,session:{...x,scope:await WA.scope(ctx,course),day:WA.day(at),challenge,teacher_id:s.profile.device,roster:s.snapshot.roster.filter(r=>WA.sameCtx(r,ctx)).map(r=>r.nim)}});},{ctx,course});await drained(page);const s=await page.evaluate(()=>WA.get()),m=s.snapshot.marks.find(m=>m.scope===session.scope&&m.slot===2&&m.nim===fixture.nim);assert.equal(m.mark,'A');const expired=s.snapshot.sessions.find(x=>x.scope===session.scope&&x.slot===2);await assert.rejects(()=>sp.evaluate(async x=>{const s=await WA.get(),reply=await WA.seal({v:1,type:'reply',device:s.profile.device,session:x.id,nonce:WA.decode(x.challenge.split('.')[0]).nonce,mark:'.',reason:'',location:null,at:Date.now()});return WA.submitReply(WA.qr('reply',s.profile.certificate,'reply',reply));},expired),/berakhir|waktu/i);});
 await t.test('revision conflict keeps unsynced edit for review',async()=>{await page.evaluate(async({ctx,course,nim})=>{await WA.queue({type:'mark',ctx,matkul:course,nim,slot:2,mark:'.',baseRevision:0});await WA.sync();},{ctx,course,nim:fixture.nim});await waitFor(page,async()=>(await WA.get()).outbox.some(x=>x.problem));const s=await page.evaluate(()=>WA.get()),o=s.outbox.find(x=>x.problem);assert.equal(o.problem.status,'conflict');await page.evaluate(id=>WA.resolve(id,false),o.id);});
 await page.evaluate(()=>WA.prepareOffline());await waitFor(page,async()=>!!(await caches.match(new URL('app/offline-ready',WA.ROOT).href)),null,60000);
 await t.test('worksheet edits persist offline and sync on reconnect',async()=>{await page.locator('#sessionForm [name=matkul]').fill(course);await page.locator('[data-page=absen]').click();const frame=page.frameLocator('#worksheet');await frame.locator('#tbodySiswa tr:not(.page-preview-only)').first().waitFor();await teacher.setOffline(true);await frame.locator('.attendance-cell').nth(2).fill('I');await page.waitForTimeout(1000);assert((await page.evaluate(()=>WA.get())).outbox.some(x=>x.type==='mark'));await page.locator('#closeScreen').click();await teacher.setOffline(false);await drained(page);});
 await t.test('blank course/time and signature separation survive print layout',async()=>{const exam=await teacher.newPage();exam.on('pageerror',e=>errors.push(e.message));await exam.goto(BASE+'ujian.php?'+new URLSearchParams(ctx));await exam.waitForFunction(()=>!!window.pastikanJarakTandaTangan);assert.equal(await exam.locator('[data-edit-key=room-label]').innerText(),'');assert.equal(await exam.locator('[data-edit-key=time-label]').innerText(),'');assert.equal(await exam.locator('[data-app-course]').innerText(),'');await exam.evaluate(()=>{document.getElementById('examScaleBlock').style.transform='translate(0px,70px)';window.pastikanJarakTandaTangan();});for(const media of ['screen','print']){await exam.emulateMedia({media});const gap=await exam.evaluate(()=>Math.min(...Array.from(document.querySelectorAll('.signature-box')).map(e=>e.getBoundingClientRect().top))-document.getElementById('examScaleBlock').getBoundingClientRect().bottom);assert(gap>=19,media+': signature gap '+gap);}await exam.close();});
 await t.test('manual attendance recorded before a QR session stops its countdown',async()=>{
  await page.evaluate(async({ctx,course,nim})=>{const s=await WA.get(),scope=await WA.scope(ctx,course),old=s.snapshot.marks.find(m=>m.scope===scope&&m.slot===3&&m.nim===nim);await WA.queue({type:'mark',ctx,matkul:course,nim,slot:3,mark:'I',baseRevision:old?.revision||0});},{ctx,course,nim:fixture.nim});await drained(page);
  const x=await page.evaluate(async({ctx,course})=>WA.startSession(ctx,course,3,2),{ctx,course});await drained(page);await sp.evaluate(()=>WA.sync());
  const mark=(await sp.evaluate(()=>WA.get())).snapshot.marks.find(m=>m.scope===x.scope&&m.slot===3&&m.nim===fixture.nim);
  assert.equal(mark.mark,'I');assert.equal(mark.session_id,null);
  await waitFor(sp,id=>!document.querySelector('[data-active-session="'+id+'"]'),x.id);
  const qr=await page.evaluate(async x=>WA.qr('session',(await WA.get()).profile.certificate,'challenge',x.challenge),x);
  await sp.locator('#scanSession').click();await sp.locator('#qrText').fill(qr);await sp.locator('#readText').click();
  await sp.locator('#studentSession').getByText('Absen diterima.',{exact:false}).waitFor();assert.equal(await sp.locator('#replyForm').count(),0);
 });
 await t.test('QR attendance removes only its own countdown and reply form',async()=>{
  const x=await page.evaluate(async({ctx,course})=>WA.startSession(ctx,course,4,2),{ctx,course});await drained(page);
  const other=await page.evaluate(async({ctx,course})=>WA.startSession(ctx,course+'-lain',4,2),{ctx,course});await drained(page);await sp.evaluate(()=>WA.sync());
  await sp.locator('[data-active-session="'+x.id+'"] .sessionClock').waitFor();await sp.locator('[data-active-session="'+other.id+'"] .sessionClock').waitFor();
  const qr=await page.evaluate(async x=>WA.qr('session',(await WA.get()).profile.certificate,'challenge',x.challenge),x);
  await sp.locator('#scanSession').click();await sp.locator('#qrText').fill(qr);await sp.locator('#readText').click();await sp.locator('#replyForm button').click();
  await waitFor(sp,id=>!document.querySelector('[data-active-session="'+id+'"]'),x.id);
  await sp.locator('#studentSession').getByText('Absen diterima.',{exact:false}).waitFor();assert.equal(await sp.locator('#replyForm').count(),0);
  assert.equal(await sp.locator('[data-active-session="'+other.id+'"] .sessionClock').count(),1);
  const mark=(await sp.evaluate(()=>WA.get())).snapshot.marks.find(m=>m.session_id===x.id&&m.nim===fixture.nim);assert.equal(mark.mark,'.');
 });
 await t.test('manual attendance closes an existing notification without scanning QR',async()=>{
  await sp.evaluate(()=>{window.testNotices=new Map();window.testClosed=[];window.Android={notifySession:(id,title,body)=>testNotices.set(id,{title,body}),attendanceAccepted:id=>{testNotices.delete(id);testClosed.push(id);}};});
  const x=await page.evaluate(async({ctx,course})=>WA.startSession(ctx,course,5,2),{ctx,course});await drained(page);await sp.evaluate(()=>WA.sync());
  await waitFor(sp,id=>testNotices.has(id),x.id);
  await page.evaluate(async({ctx,course,nim})=>WA.queue({type:'mark',ctx,matkul:course,nim,slot:5,mark:'.',baseRevision:0}),{ctx,course,nim:fixture.nim});await drained(page);await sp.evaluate(()=>WA.sync());
  await waitFor(sp,id=>testClosed.includes(id)&&!testNotices.has(id)&&!document.querySelector('[data-active-session="'+id+'"]'),x.id);
  await sp.evaluate(()=>{delete window.Android;});
 });
 await t.test('inserted rows and columns persist across offline reload',async()=>{await Promise.all([page.waitForEvent('framenavigated',f=>f.url().includes('absen.php')),page.locator('[data-page=absen]').click()]);const frame=page.frames().find(f=>f.url().includes('absen.php'));await waitFor(frame,()=>window.WASheetReady===true);await teacher.setOffline(true);const n=await frame.locator('#tbodySiswa tr:not(.page-preview-only)').count();await frame.locator('#tourBtnTambah').click();await frame.locator('#tourBtnKolom').click();const row=frame.locator('#tbodySiswa tr:not(.page-preview-only)').last();await row.locator('input').nth(0).fill('QAINSERT'+suffix);await row.locator('input').nth(1).fill('Nama baris sisipan');await row.locator('input').nth(1).blur();await waitFor(page,async({course,nim})=>(await WA.get()).snapshot.documents.some(d=>d.matkul===course&&d.kind==='attendance-sheet'&&d.content.table?.head.flat().some(c=>c.id==='headerPertemuan'&&c.colspan===17)&&d.content.table.rows.some(r=>r[1]===nim&&r[2]==='Nama baris sisipan')),{course,nim:'QAINSERT'+suffix});await frame.evaluate(()=>location.reload());await waitFor(frame,()=>window.WASheetReady===true&&Array.from(document.querySelectorAll('#tbodySiswa input')).some(i=>i.value==='Nama baris sisipan'));assert.equal(await frame.locator('#tbodySiswa tr:not(.page-preview-only)').count(),n+1);assert.equal(await frame.locator('#headerPertemuan').getAttribute('colspan'),'17');await page.locator('#closeScreen').click();await teacher.setOffline(false);await drained(page);});
 await t.test('recap preserves names and only four A force E',async()=>{await Promise.all([page.waitForEvent('framenavigated',f=>f.url().includes('absen.php')),page.locator('[data-page=absen]').click()]);const frame=page.frames().find(f=>f.url().includes('absen.php'));await waitFor(frame,()=>window.WASheetReady===true);const result=await frame.evaluate(()=>{const row=document.querySelector('#tbodySiswa tr:not(.page-preview-only)'),cells=row.querySelectorAll('.attendance-cell');for(const c of cells)c.value='.';for(let i=0;i<4;i++)cells[i].value=i%2?'I':'S';bukaRekapNilai();let r=document.querySelector('#tbodyRekapNilai tr');for(const i of r.querySelectorAll('.score-input'))i.value='100';hitungSkorBaris(r.querySelector('input'));const first={name:r.querySelector('.name-value').textContent,s:r.querySelector('.sakit-count').textContent,i:r.querySelector('.izin-count').textContent,absent:r.querySelector('.absent-count').textContent,grade:r.querySelector('.nilai-huruf').textContent};for(let i=0;i<4;i++)cells[i].value='A';bukaRekapNilai();r=document.querySelector('#tbodyRekapNilai tr');for(const i of r.querySelectorAll('.score-input'))i.value='100';hitungSkorBaris(r.querySelector('input'));return {first,forced:r.querySelector('.nilai-huruf').textContent};});assert(result.first.name.length>1);assert.equal(result.first.s,'2');assert.equal(result.first.i,'2');assert.equal(result.first.absent,'4');assert.notEqual(result.first.grade,'E');assert.equal(result.forced,'E');await page.locator('#closeScreen').click();});
 await t.test('unchanged snapshots avoid downloading and repainting the roster',async()=>{await drained(page);const result=await page.evaluate(async()=>{const s=await WA.get();return WA.api('snapshot',{knownTag:s.snapshot.tag});});assert.equal(result.unchanged,true);assert.equal(result.snapshot,undefined);});
 await t.test('logout clears persistent account and offline access',async()=>{await page.evaluate(()=>WA.logout());assert.equal((await page.evaluate(()=>WA.get())).profile,null);await page.reload();await page.waitForSelector('#login');});
 assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
