/* Real 1.0.5 assets reproduce the old ignoreSearch service-worker cache.
   All records and servers are isolated fixtures on loopback; no hosting login. */
const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const{chromium}=require(process.env.WA_PLAYWRIGHT_PATH||'/workspace/cloud-web-absensi/browser-tools/node_modules/playwright-core');
const root=path.resolve(__dirname,'..'),version=require('../package.json').version;
for(const width of[1280,393])test('upgrade from cached 1.0.5 keeps deleted identities out of all sheets at width '+width,{timeout:120000},async()=>{
 let upgraded=false;const hits=[];
 const legacy={'app-sw.js':'legacy-cache-worker-1.0.5.js','app/core.js':'legacy-core-1.0.5.js','assets/offline-bridge.js':'legacy-offline-bridge-1.0.5.js'};
 const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://local'),p=u.pathname.slice(1)||'index.php';if(p==='app_api.php'){res.writeHead(503);res.end('{}');return;}const file=/^(index|absen|data_siswa|ujian)\.php$/.test(p)?'app/templates/'+p.replace('.php','.html'):p==='app/'?'app/index.html':p;
 try{let data=fs.readFileSync(!upgraded&&legacy[file]?path.join(__dirname,'fixtures',legacy[file]):path.join(root,file));if(!upgraded&&file.startsWith('app/templates/'))data=Buffer.from(data.toString().replace(/<script src="app\/runtime-teacher-[^"]+" defer><\/script>/,'<script src="app/core.js" defer></script><script src="assets/offline-bridge.js" defer></script><script src="assets/teacher-tools.js" defer></script>'));hits.push(p);res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(data);}catch(_){res.writeHead(404);res.end('missing');}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+'/',browser=await chromium.launch({executablePath:process.env.WA_CHROMIUM||'/usr/bin/chromium',headless:true,args:['--no-sandbox']}),context=await browser.newContext({viewport:{width,height:900}}),p=await context.newPage(),ctx={prodi:'Pendidikan Teknologi Informasi',semester:'1',kelas:'A'};
 try{await context.route('**/*',r=>new URL(r.request().url()).origin===new URL(base).origin?r.continue():r.abort());p.on('dialog',d=>d.accept());await p.goto(base+'index.php');await p.waitForFunction(()=>window.WA);await p.evaluate(ctx=>WA.change(s=>({...s,profile:{role:'teacher',device:'cache-test',account:{nama:'Cache test'}},snapshot:{roster:[{...ctx,id:1,nim:'KEEP123',nama:'Mahasiswa tetap','jk':'L'},{...ctx,kelas:'B',id:2,nim:'OTHER123',nama:'Kelas lain',jk:'P'}],documents:[],marks:[],sessions:[],registrations:[]}})),ctx);
 await p.evaluate(()=>WA.prepareOffline());await p.waitForFunction(async()=>!!await caches.match(new URL('app/offline-ready',WA.ROOT).href));await p.reload();await p.waitForFunction(()=>navigator.serviceWorker.controller&&window.WASheetReady);
 await p.evaluate(async ctx=>{const sc=await WA.scope(ctx,'Cache');await WA.change(s=>{s.snapshot.documents.push({scope:sc,ctx,matkul:'Cache',kind:'attendance-sheet',content:{text:{'#metaLeftBox .meta-row:nth-child(2) .meta-val':'2028/2029'},table:{head:[[{text:'NO'},{text:'NIM'},{text:'NAMA'},{text:'L/P'},{text:'TANGGAL',colspan:16,id:'headerPertemuan'},{text:'KET'}],[],[]],rows:[[1,'GONE123','Mahasiswa sudah dihapus','L',...Array(16).fill(''),''],[2,'KEEP123','Mahasiswa tetap','L','.',...Array(15).fill(''),'']]}}});s.snapshot.marks.push({scope:sc,nim:'KEEP123',slot:1,mark:'.'});return s;});},ctx);
 const url=page=>base+page+'.php?'+new URLSearchParams({...ctx,matkul:'Cache'});
 await p.goto(url('absen'));await p.waitForFunction(()=>window.WASheetReady);assert.equal(await p.locator('#tbodySiswa .nim-input').count(),2,'the historical cache actually reproduces the ghost row');
 upgraded=true;await p.goto(url('data_siswa'));await p.waitForFunction(()=>window.WASheetReady);assert.equal(await p.locator('#tabelSiswa .student-row').count(),1);assert(hits.includes('app/runtime-teacher-'+version+'.js'));
 await p.goto(url('absen'));await p.waitForFunction(()=>window.WASheetReady);assert.equal(await p.locator('#tbodySiswa .nim-input').count(),1);assert.equal(await p.locator('#tbodySiswa .nim-input').inputValue(),'KEEP123');assert.equal(await p.locator('.attendance-cell').first().inputValue(),'.');assert.equal(await p.locator('#metaLeftBox .meta-val').nth(1).innerText(),'2028/2029');await p.evaluate(()=>bukaRekapNilai());assert.equal(await p.locator('#tbodyRekapNilai tr').count(),1);
 // Activation must not reload an edited page; pending drafts and private cache survive.
 await p.evaluate(()=>WA.prepareOffline());await p.waitForFunction(async()=>Array.from(await caches.keys()).some(n=>n.includes('cache-roster-7')));await p.waitForFunction(async()=>!!await caches.match(new URL('app/offline-ready',WA.ROOT).href));
 await context.setOffline(true);await p.reload();await p.waitForFunction(()=>window.WASheetReady);assert.equal(await p.locator('#tbodySiswa .nim-input').count(),1,'legacy private HTML also receives the current entry point offline');assert.equal(await p.locator('.attendance-cell').first().inputValue(),'.');
 // Rapid deletion followed by navigation must await the entire durable deletion.
 await p.evaluate(()=>{window.confirm=()=>true;document.querySelector('[name=aksi_hapus_massal_kelas]').form.requestSubmit();document.querySelector('a[href*="ujian.php"]').click();});await p.waitForURL(u=>u.pathname.endsWith('/ujian.php'));await p.waitForFunction(()=>window.WASheetReady);assert.equal(await p.locator('#examTableBlock tbody tr').count(),0);
 const s=await p.evaluate(()=>WA.get());assert.equal(s.snapshot.roster.length,1);assert.equal(s.snapshot.roster[0].nim,'OTHER123');assert(s.outbox.some(o=>o.type==='student-delete'&&o.nim==='KEEP123'));assert(s.snapshot.marks.some(m=>m.nim==='KEEP123'&&m.mark==='.'),'historical attendance is preserved');
 await p.goto(url('absen'));await p.waitForFunction(()=>window.WASheetReady);assert.equal(await p.locator('#tbodySiswa .nim-input').count(),0);await p.evaluate(()=>bukaRekapNilai());assert.equal(await p.locator('#tbodyRekapNilai tr').count(),0);await p.goto(url('data_siswa'));await p.waitForFunction(()=>window.WASheetReady);assert.equal(await p.locator('#tabelSiswa .student-row').count(),0);
 // Closing a renderer before its asynchronous batch writes must recover the deletion.
 await p.evaluate(ctx=>WA.change(s=>{s.snapshot.roster.push(...['INTERRUPT1','INTERRUPT2'].map((nim,i)=>({...ctx,id:i+100,nim,nama:'Interrupted '+i,jk:'L'})));return s;}),ctx);await p.goto(url('data_siswa'));await p.waitForFunction(()=>window.WASheetReady&&document.querySelectorAll('#tabelSiswa .student-row').length===2);
 await p.evaluate(()=>{const original=WA.deleteStudents;WA.deleteStudents=async(...args)=>{await new Promise(resolve=>setTimeout(resolve,10000));return original(...args);};window.confirm=()=>true;document.querySelector('a[href*=hapus_semua]').click();});assert.equal((await p.evaluate(()=>WA.get())).snapshot.roster.length,3,'the batch has not yet written');await p.close();const recovered=await context.newPage();await recovered.goto(url('absen'));await recovered.waitForFunction(()=>window.WASheetReady);assert.equal(await recovered.locator('#tbodySiswa .nim-input').count(),0);const after=await recovered.evaluate(()=>WA.get());assert.equal(after.snapshot.roster.length,1);assert.equal(after.snapshot.roster[0].nim,'OTHER123');assert.equal(after.outbox.filter(o=>o.type==='student-delete'&&o.nim.startsWith('INTERRUPT')).length,2);await recovered.reload();await recovered.waitForFunction(()=>window.WASheetReady);assert.equal((await recovered.evaluate(()=>WA.get())).outbox.filter(o=>o.type==='student-delete'&&o.nim.startsWith('INTERRUPT')).length,2,'recovery does not duplicate deletion operations');
 }finally{await browser.close();await new Promise(r=>server.close(r));}
});
