const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.WA_PLAYWRIGHT_PATH||'/workspace/cloud-web-absensi/browser-tools/node_modules/playwright-core');
const BASE=process.env.WA_TEST_URL||'http://127.0.0.1:8000/';if(!['127.0.0.1','localhost'].includes(new URL(BASE).hostname))throw Error('Fixture tests require the local server.');
test('floating guides, imported row order and real image recognition',{timeout:240000},async t=>{
 const browser=await chromium.launch({executablePath:process.env.WA_CHROMIUM||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const teacher=await browser.newContext(),student=await browser.newContext();const errors=[];
 try{for(const c of [teacher,student])await c.route('**/*',r=>new URL(r.request().url()).origin===new URL(BASE).origin?r.continue():r.abort());const p=await teacher.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(BASE+'index.php');await p.waitForFunction(()=>!!window.WA);const source=fs.readFileSync(path.join(__dirname,'../index.php'),'utf8');await p.evaluate(fields=>WA.login('teacher',fields),{username:source.match(/\$user === '([^']+)'/)[1],password:source.match(/\$pass === '([^']+)'/)[1]});
 const ctx={prodi:'Pendidikan Bahasa Inggris',semester:'8',kelas:'E'},suffix=Date.now();
 await t.test('guide available on every original page; status and minimized state survive navigation',async()=>{
  for(const page of ['index','data_siswa','absen','ujian','music_player']){await p.goto(BASE+page+'.php?'+new URLSearchParams(ctx));await p.locator('.wa-guide-open').waitFor();await p.locator('.wa-guide-open').click();await p.locator('.wa-guide-panel:not([hidden])').waitFor();await p.locator('.wa-guide-panel img').evaluate(img=>img.decode());await p.locator('.wa-guide-close').click();}
  await p.goto(BASE+'absen.php?'+new URLSearchParams(ctx));await p.waitForFunction(()=>window.WASheetReady);assert.equal(await p.locator('#waStatus').isVisible(),false);await p.setViewportSize({width:393,height:852});await p.locator('.wa-guide-open').click();await p.locator('.wa-guide-status-toggle').check();assert.equal(await p.locator('#waStatus').isVisible(),true);await p.locator('.wa-guide-status-toggle').uncheck();const geometry=await p.evaluate(()=>{const a=document.querySelector('#openAttendanceQR').getBoundingClientRect(),b=document.querySelector('.wa-guide-panel').getBoundingClientRect();return {fits:b.left>=0&&b.right<=innerWidth&&b.top>=0&&b.bottom<=innerHeight,overlap:a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top};});assert(geometry.fits);assert.equal(geometry.overlap,false);await p.locator('.wa-guide-close').click();await p.locator('.wa-guide-hide').click();await p.reload();assert(await p.locator('.wa-guide-dock').evaluate(x=>x.classList.contains('is-small')));await p.locator('.wa-guide-open').click();await p.locator('.wa-guide-open').click();await p.locator('.wa-guide-close').click();await p.setViewportSize({width:1280,height:900});
 });
 await t.test('student guide is usable inside the QR dialog and contains no teacher controls',async()=>{const sp=await student.newPage();sp.on('pageerror',e=>errors.push(e.message));await sp.goto(BASE+'app/?role=student');await sp.locator('#login').waitFor();await sp.locator('.wa-guide-open').click();assert.equal(await sp.locator('.wa-guide-panel select option').count(),4);assert(!/dosen.*setujui|cadangkan|rekap nilai/i.test(await sp.locator('.wa-guide-panel select').innerText()));await sp.locator('.wa-guide-close').click();await sp.evaluate(()=>document.getElementById('scanner').showModal());await sp.locator('#scanner .wa-guide-open').click();await sp.locator('.wa-guide-panel select').selectOption('1');await sp.locator('.wa-guide-next').click();assert.equal(await sp.locator('.wa-guide-target').isVisible(),true);await sp.locator('.wa-guide-close').click();await sp.locator('#stopScan').click();await sp.close();});
 await p.goto(BASE+'data_siswa.php?'+new URLSearchParams(ctx));await p.waitForFunction(()=>window.WASheetReady);
 await t.test('real OCR retains wrapped names, numeric and prefixed NIMs, missing identities and source order',async()=>{
  const rows=await p.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=580;const g=canvas.getContext('2d');g.fillStyle='white';g.fillRect(0,0,1200,580);g.strokeStyle='black';g.lineWidth=2;for(const x of [5,80,400,1100,1195]){g.beginPath();g.moveTo(x,5);g.lineTo(x,555);g.stroke();}for(const y of [5,95,210,325,440,555]){g.beginPath();g.moveTo(5,y);g.lineTo(1195,y);g.stroke();}g.fillStyle='black';g.font='26px Arial';g.fillText('NO',15,60);g.fillText('NIM',100,60);g.fillText('NAMA MAHASISWA',425,60);g.fillText('L/P',1115,60);const data=[['C12345678901','ZULFA RAHMAWATI','PUTRI','P'],['12345678902','ANA SAFITRI','','P'],['C12345678903','BUDI SANTOSO','','L'],['','RINA AMALIA','','P']];data.forEach((r,i)=>{const y=145+i*115;g.fillText(String(i+1),20,y);g.fillText(r[0],100,y);g.fillText(r[1],425,y);if(r[2])g.fillText(r[2],425,y+34);g.fillText(r[3],1130,y);});const worker=await buatWorkerDaftar();try{return await pindaiKanvasDaftar(canvas,worker);}finally{await worker.terminate();}});
  assert.equal(rows.length,4,JSON.stringify(rows.map(r=>({nim:r.nim,nama:r.nama}))));assert.equal(rows[0].nim,'C12345678901');assert.equal(rows[0].nama,'ZULFA RAHMAWATI PUTRI');assert.equal(rows[1].nim,'C12345678902');assert.equal(rows[1].nama,'ANA SAFITRI');assert.equal(rows[2].nim,'C12345678903');assert.equal(rows[3].nim,'');assert.equal(rows[3].nama,'RINA AMALIA');assert(rows.every(r=>r.preview?.startsWith('data:image/png;')));await p.evaluate(rows=>tampilkanHasilOcr(rows),rows);assert.equal(await p.locator('#ocrReviewRows img').count(),4);await p.locator('#btnSimpanOcr').click();assert.equal(await p.locator('#ocrReviewRows tr').count(),4);assert.equal(await p.evaluate(()=>document.activeElement.getAttribute('aria-label')),'NIM baris 4');
 });
 await t.test('reviewed import order survives synchronization and original roster/sheet reload',async()=>{
  const rows=[{nim:'ORDERZ'+suffix,nama:'Zulfa urutan pertama',jk:'P'},{nim:'ORDERA'+suffix,nama:'Ana urutan kedua',jk:'P'}];await p.evaluate(async({rows,ctx})=>{const form=new FormData();form.append('rows',JSON.stringify(rows));const response=await fetch('data_siswa.php?aksi=import_siswa&'+new URLSearchParams(ctx),{method:'POST',body:form});if(!(await response.json()).inserted)throw Error('Import failed');await WA.sync();},{rows,ctx});await p.waitForFunction(async()=>!(await WA.get()).outbox.length);for(const page of ['data_siswa','absen','ujian']){await p.goto(BASE+page+'.php?'+new URLSearchParams(ctx));await p.waitForFunction(()=>window.WASheetReady);const ordered=await p.evaluate(()=>Array.from(document.querySelectorAll('tbody tr')).flatMap(row=>{const el=row.cells[1]?.querySelector('input');const value=el?.value||row.cells[1]?.textContent||'';return value.startsWith('ORDER')?[value]:[];}));assert(ordered.indexOf(rows[0].nim)<ordered.indexOf(rows[1].nim),page+': '+ordered);}
 });assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
