const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const{chromium}=require(process.env.WA_PLAYWRIGHT_PATH||'/workspace/cloud-web-absensi/browser-tools/node_modules/playwright-core');
const BASE=process.env.WA_TEST_URL||'http://127.0.0.1:8000/';if(!['127.0.0.1','localhost'].includes(new URL(BASE).hostname))throw Error('Deletion fixtures require the local server.');
test('deleted students stay absent across saved sheets, recap, tabs, offline deletion and reconnect',{timeout:150000},async t=>{
 const browser=await chromium.launch({executablePath:process.env.WA_CHROMIUM||'/usr/bin/chromium',headless:true,args:['--no-sandbox']}),context=await browser.newContext(),errors=[],ctx={prodi:'Pendidikan Sejarah',semester:'8',kelas:'E'},other={...ctx,kelas:'D'},stamp=Date.now(),a='DELETEA'+stamp,b='DELETEB'+stamp,sentinel='KEEP'+stamp,course='DELETE-'+stamp;
 try{await context.route('**/*',r=>new URL(r.request().url()).origin===new URL(BASE).origin?r.continue():r.abort());const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto(BASE+'index.php');await p.waitForFunction(()=>!!window.WA);const source=fs.readFileSync(path.join(__dirname,'../index.php'),'utf8');await p.evaluate(fields=>WA.login('teacher',fields),{username:source.match(/\$user === '([^']+)'/)[1],password:source.match(/\$pass === '([^']+)'/)[1]});
 async function drained(){await p.evaluate(()=>WA.sync());await p.waitForFunction(async()=>!(await WA.get()).outbox.length);}
 async function add(nim,context=ctx){await p.evaluate(({nim,ctx})=>WA.queue({type:'student-upsert',ctx,nim,nama:'Nama '+nim,jk:'L'}),{nim,ctx:context});}
 async function goto(page,target=p){await target.goto(BASE+page+'.php?'+new URLSearchParams({...ctx,matkul:course}));await target.waitForFunction(()=>window.WASheetReady===true);}
 await p.evaluate(async ctx=>{for(const row of (await WA.get()).snapshot.roster.filter(r=>WA.sameCtx(r,ctx)))await WA.queue({type:'student-delete',ctx,nim:row.nim});},ctx);await drained();await add(a);await add(b);await add(sentinel,other);await drained();await goto('absen');await p.evaluate(async({ctx,course,a,b})=>{await WA.saveDocument(ctx,course,'attendance-sheet',{table:{head:Array.from(document.querySelector('#tabelAbsen').tHead.rows).map(row=>Array.from(row.cells).map(c=>({text:c.textContent,colspan:c.colSpan,rowspan:c.rowSpan,id:c.id,cls:c.className}))),rows:[[1,'DELETED-LEGACY','Ghost student','L',...Array(16).fill(''),''],...Array.from(document.querySelector('#tbodySiswa').rows).map(r=>Array.from(r.cells).map(c=>c.querySelector('input')?.value??c.textContent))]},text:{'#metaLeftBox .meta-row:nth-child(2) .meta-val':'2028/2029'}});await WA.saveDocument(ctx,course,'grade',{data_nilai:[{nim:a,skor_akhir:70},{nim:b,skor_akhir:88}]});await WA.queue({type:'mark',ctx,matkul:course,nim:b,slot:1,mark:'.',baseRevision:0});},{ctx,course,a,b});await drained();await p.reload();await p.waitForFunction(()=>window.WASheetReady);
 await t.test('old saved table cannot restore a NIM absent from the authoritative roster',async()=>{assert.equal(await p.locator('#tbodySiswa .nim-input').count(),2);assert.equal(await p.locator('#tbodySiswa').innerText().then(x=>x.includes('Ghost student')),false);assert.equal(await p.locator('#metaLeftBox .meta-val').nth(1).innerText(),'2028/2029');});
 const sheet=await context.newPage(),exam=await context.newPage();for(const tab of[sheet,exam]){tab.on('pageerror',e=>errors.push(e.message));tab.on('dialog',d=>d.accept());}await goto('absen',sheet);await sheet.evaluate(()=>bukaRekapNilai());await goto('ujian',exam);await goto('data_siswa');
 await t.test('single deletion updates already open attendance, recap and exam while preserving the other student',async()=>{await p.locator('#tabelSiswa tbody tr').filter({hasText:a}).locator('button,a').filter({hasText:/^Hapus$/}).click();await drained();await sheet.waitForFunction(nim=>!Array.from(document.querySelectorAll('#tbodySiswa .nim-input')).some(el=>el.value===nim),a);await exam.waitForFunction(nim=>!document.querySelector('#examTableBlock tbody').textContent.includes(nim),a);assert.equal(await p.locator('#ocrReviewRows tr').count(),0);assert.equal(await p.locator('#tabelSiswa .student-row').count(),1);assert.equal(await sheet.locator('#tbodyRekapNilai tr').count(),1);assert.equal(await sheet.locator('#tbodyRekapNilai .nim-value').innerText(),b);assert.equal(await sheet.locator('#tbodySiswa .attendance-cell').first().inputValue(),'.');assert.equal(await exam.locator('#examTableBlock tbody tr').count(),1);assert((await exam.locator('#examTableBlock tbody').innerText()).includes('88'));await sheet.reload();await sheet.waitForFunction(()=>window.WASheetReady);assert.equal(await sheet.locator('#tbodySiswa .nim-input').count(),1);assert.equal(await sheet.locator('#tbodySiswa .nim-input').inputValue(),b);});
 await t.test('deleting an already removed identity on another device is idempotent',async()=>{const result=await p.evaluate(({ctx,a})=>WA.api('sync',{operations:[{id:crypto.randomUUID(),type:'student-delete',ctx,nim:a,base:{nama:'Nama '+a}}]}),{ctx,a});assert.equal(result.results[0].status,'success');});
 await p.evaluate(()=>WA.prepareOffline());await p.waitForFunction(async()=>!!await caches.match(new URL('app/offline-ready',WA.ROOT).href));await goto('absen');
 await t.test('permanent single deletion works offline and remains deleted after reconnection',async()=>{await context.setOffline(true);await p.evaluate(nim=>{document.querySelector('[name=hapus_permanen_id]').value=nim;document.querySelector('[name=aksi_hapus_permanen]').form.requestSubmit();},b);await p.waitForFunction(()=>!document.querySelector('#tbodySiswa .nim-input'));await p.reload();await p.waitForFunction(()=>window.WASheetReady);assert.equal(await p.locator('#tbodySiswa .nim-input').count(),0);await context.setOffline(false);await drained();for(const page of['data_siswa','absen','ujian']){await goto(page);assert.equal(await p.locator(page==='data_siswa'?'.student-row':page==='absen'?'#tbodySiswa .nim-input':'#examTableBlock tbody tr').count(),0,page);}});
 await t.test('bulk deletion from the original roster control reaches every sheet and leaves another class intact',async()=>{await add(a);await add(b);await drained();await goto('data_siswa');await p.locator('a[href*="hapus_semua"]').click();await drained();for(const page of['data_siswa','absen','ujian'])await goto(page);const state=await p.evaluate(()=>WA.get());assert(!state.snapshot.roster.some(r=>WACompare(r)));function WACompare(r){return r.prodi===ctx.prodi&&r.semester===ctx.semester&&r.kelas===ctx.kelas;}assert(state.snapshot.roster.some(r=>r.nim===sentinel));await goto('absen');await p.evaluate(()=>bukaRekapNilai());assert.equal(await p.locator('#tbodyRekapNilai tr').count(),0);});
 assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
