const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.WA_PLAYWRIGHT_PATH||'/workspace/cloud-web-absensi/browser-tools/node_modules/playwright-core');
const BASE=process.env.WA_TEST_URL||'http://127.0.0.1:8000/';if(!['127.0.0.1','localhost'].includes(new URL(BASE).hostname))throw Error('Sheet fixtures require the local server.');
function checkGeometry(){
 const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'),failures=[];
 for(const el of document.querySelectorAll('#paperSheet .meta-val,#paperSheet .meta-value,#paperSheet .meta-label,#tabelAbsen input,#examTableBlock th,#examTableBlock td,#examScaleBlock th,#examScaleBlock td,#tabelRekapNilai th,#tabelRekapNilai td')){
  if(!el.getClientRects().length||el.querySelector('input'))continue;const value=(el.matches('input')?el.value:el.textContent).replace(/\s+/g,' ').trim();if(!value)continue;
  const s=getComputedStyle(el),width=el.clientWidth-parseFloat(s.paddingLeft)-parseFloat(s.paddingRight);ctx.font=`${s.fontStyle} ${s.fontWeight} ${s.fontSize} ${s.fontFamily}`;const text=s.textTransform==='uppercase'?value.toUpperCase():value;
  if(ctx.measureText(text).width>width+1)failures.push({text:value,width,needed:ctx.measureText(text).width,font:s.fontSize});
  if(s.whiteSpace!=='nowrap'&&el.tagName!=='INPUT')failures.push({text:value,wrap:s.whiteSpace});
 }
 return failures;
}
test('single-line sheet text, cell spacing and Office exports',{timeout:180000},async t=>{
 const browser=await chromium.launch({executablePath:process.env.WA_CHROMIUM||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{
 const context=await browser.newContext({viewport:{width:1280,height:900}});await context.route('**/*',r=>new URL(r.request().url()).origin===new URL(BASE).origin?r.continue():r.abort());const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(BASE+'index.php');await p.waitForFunction(()=>!!window.WA);const source=fs.readFileSync(path.join(__dirname,'../index.php'),'utf8');await p.evaluate(f=>WA.login('teacher',f),{username:source.match(/\$user === '([^']+)'/)[1],password:source.match(/\$pass === '([^']+)'/)[1]});
 const ctx={jenjang:'S1',prodi:'Pendidikan Sejarah',semester:'7',kelas:'D'},nim='C'+String(Date.now())+'012345',name='Muhammad Fadillah Nur Rahman Pratama',course='Algoritma dan Pemrograman Komputer';await p.evaluate(async row=>{await WA.queue({type:'student-upsert',ctx:row,...row});await WA.sync();},{...ctx,nim,nama:name,jk:'L'});
 const exports=[];
 await t.test('attendance fits long identities with padding on desktop, phone and print',async()=>{
  await p.goto(BASE+'absen.php?'+new URLSearchParams({...ctx,matkul:course}));await p.waitForFunction(()=>window.WASheetReady);
  for(const width of [1280,393]){await p.setViewportSize({width,height:900});for(const media of ['screen','print']){await p.setViewportSize({width:media==='print'?794:width,height:900});await p.emulateMedia({media});await p.waitForTimeout(400);await p.evaluate(()=>WAFitSheetText());assert.deepEqual(await p.evaluate(checkGeometry),[],width+' '+media);const dimensions=await p.evaluate(()=>{const table=document.getElementById('tabelAbsen'),paper=document.getElementById('tableWrapper');return {table:table.getBoundingClientRect().width,paper:paper.getBoundingClientRect().width,padding:parseFloat(getComputedStyle(table.rows[3].cells[1]).paddingLeft)};});assert(dimensions.padding>=6);assert(dimensions.table<=dimensions.paper+2,JSON.stringify(dimensions));}}
  await p.emulateMedia({media:'screen'});await p.setViewportSize({width:1280,height:900});exports.push({name:'attendance Word',html:await p.evaluate(()=>buatDokumenWord(document.getElementById('paperSheet'),'Lembar Absen')),width:734});exports.push({name:'attendance Excel',html:await p.evaluate(()=>buatTabelExcel(document.getElementById('tabelAbsen'),'Absensi')),width:1600});
 });
 await t.test('recap stays readable and scrolls; exporting keeps column widths and complete identities',async()=>{
  await p.evaluate(()=>bukaRekapNilai());await p.evaluate(()=>WAFitSheetText());assert.deepEqual(await p.evaluate(checkGeometry),[]);const geometry=await p.evaluate(()=>{const table=document.getElementById('tabelRekapNilai');return {scrolls:table.offsetWidth>table.parentElement.clientWidth,fonts:[...table.querySelectorAll('th')].map(e=>parseFloat(getComputedStyle(e).fontSize))};});assert(geometry.scrolls);assert(geometry.fonts.every(f=>f>=10));exports.push({name:'recap Excel',html:await p.evaluate(()=>buatTabelExcel(document.getElementById('tabelRekapNilai'),'Rekap Nilai')),width:2400});exports.push({name:'recap Word',html:await p.evaluate(()=>buatDokumenWord(document.getElementById('tabelRekapNilai'),'Rekap Nilai')),width:1062});await p.setViewportSize({width:1047,height:900});await p.evaluate(()=>siapkanCetakRekap());await p.emulateMedia({media:'print'});await p.waitForTimeout(400);await p.evaluate(()=>WAFitSheetText());assert.deepEqual(await p.evaluate(checkGeometry),[],'printed recap');assert(await p.locator('#tabelRekapNilai').evaluate(e=>e.getBoundingClientRect().width<=1048));await p.emulateMedia({media:'screen'});await p.evaluate(()=>selesaiCetakRekap());await p.evaluate(()=>WAFitSheetText());await p.evaluate(()=>tutupRekapNilai());await p.evaluate(()=>WAFlush());
 });
 await t.test('exam course, room and time fit one line, including print and phone',async()=>{
  await p.goto(BASE+'ujian.php?'+new URLSearchParams({...ctx,matkul:course}));await p.waitForFunction(()=>window.WASheetReady);await p.locator('[data-edit-key=room-label]').fill('Kelas A / Laboratorium Komputer');await p.locator('[data-edit-key=time-label]').fill('Senin, 08.00 – 10.30 WITA');
  for(const width of [1280,393]){await p.setViewportSize({width,height:900});for(const media of ['screen','print']){await p.setViewportSize({width:media==='print'?794:width,height:900});await p.emulateMedia({media});await p.waitForTimeout(400);await p.evaluate(()=>WAFitSheetText());assert.deepEqual(await p.evaluate(checkGeometry),[],width+' '+media);assert(await p.locator('[data-edit-key=room-label]').evaluate(e=>e.getBoundingClientRect().height<20));}}
  await p.emulateMedia({media:'screen'});exports.push({name:'exam Word',html:await p.evaluate(()=>dokumenPenuhUjian('word')),width:703});exports.push({name:'exam Excel',html:await p.evaluate(()=>dokumenPenuhUjian('excel')),width:703});
 });
 await t.test('saved Office markup fits its paper width and retains prefixed NIMs',async()=>{
  const preview=await context.newPage();for(const item of exports){assert(item.html.includes(nim),item.name+' NIM retained');assert(item.html.includes(name),item.name+' name retained');await preview.setViewportSize({width:item.width,height:900});await preview.setContent(item.html);const failures=await preview.evaluate(()=>{const result=[];for(const cell of document.querySelectorAll('th,td')){if(cell.closest('.doc-header,.export-header,.doc-signatures,.export-signatures,.doc-meta'))continue;if(cell.querySelector('table'))continue;const range=document.createRange();range.selectNodeContents(cell);const s=getComputedStyle(cell),allowed=cell.clientWidth-parseFloat(s.paddingLeft)-parseFloat(s.paddingRight);if(range.getBoundingClientRect().width>allowed+2)result.push({text:cell.textContent.trim(),width:allowed,actual:range.getBoundingClientRect().width});}return result;});assert.deepEqual(failures,[],item.name);}await preview.close();
 });
 assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
