(async()=>{
'use strict';const entryRole=window.Android?.appRole?.()||new URLSearchParams(location.search).get('role');if(entryRole!=='student'){location.replace(new URL('index.php',WA.ROOT));return;}const $=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const prodis=['Pendidikan Teknologi Informasi','Pendidikan Guru Sekolah Dasar','Pendidikan Jasmani Kesehatan dan Rekreasi','Pendidikan Bahasa dan Sastra Indonesia','Pendidikan Sejarah','Pendidikan Bahasa Inggris'];let mode='',challenge=null,qrCode='',qrSession=null,stream=null,scanHandler=null,frameTimer=null,rendering=false,resultsKey='',historyKey='',noticesKey='',clockOffset=0;const closedNotices=new Set();let draftKey='',studentDraft=null;
function saveStudentDraft(){if(!draftKey||!challenge)return;const form=$('#replyForm');studentDraft={...studentDraft,challenge,mark:form?.elements.mark.value||studentDraft?.mark||'.',reason:form?.elements.reason.value||'',replyCode:studentDraft?.replyCode||''};localStorage.setItem(draftKey,JSON.stringify(studentDraft));}

function message(text){$('#notice').textContent=text;$('#notice').style.display='block';clearTimeout(message.timer);message.timer=setTimeout(()=>$('#notice').style.display='none',7500);}
function options(values,selected){return values.map(x=>`<option value="${E(x)}" ${String(x)===String(selected)?'selected':''}>${E(x)}</option>`).join('');}
function classFields(value={},prefix=''){return `<div class="grid"><label>Jenjang<select name="${prefix}jenjang"><option>S1</option></select></label><label>Program studi<select name="${prefix}prodi">${options(prodis,value.prodi)}</select></label><label>Semester<select name="${prefix}semester">${options([1,2,3,4,5,6,7,8],value.semester||1)}</select></label><label>Kelas<select name="${prefix}kelas">${options(['A','B','C','D','E'],value.kelas||'A')}</select></label></div>`;}
function formContext(form){return WA.ctx(Object.fromEntries(new FormData(form)));}
async function run(fn,button){if(button)button.disabled=true;try{return await fn();}catch(e){message(e.message);return null;}finally{if(button)button.disabled=false;}}
function loginView(){
 $('#main').innerHTML=`<h1>Masuk mahasiswa</h1><p class="help">Masuk pertama kali dengan internet. Akun dan data absensi tetap tersimpan untuk penggunaan offline. Gunakan Keluar akun untuk mengakhiri akses perangkat.</p><section id="loginFields"></section>`;
 $('#loginFields').innerHTML=`<form id="login">${classFields()}<label>NIM<input name="nim" autocomplete="username" required placeholder="Termasuk awalan huruf, misalnya C..."></label><label>PIN 6–12 angka<input name="pin" type="password" inputmode="numeric" minlength="6" maxlength="12" pattern="[0-9]{6,12}" required autocomplete="current-password"></label><label><input name="register" type="checkbox" id="register"> Saya mahasiswa baru, daftar akun</label><div id="registration" hidden><label>Nama sesuai daftar kelas<input name="nama"></label><label>L/P<select name="jk"><option>L</option><option>P</option></select></label><p class="small">Dosen mencocokkan nama dan NIM serta menyetujui akun sekali.</p></div><button class="primary">Masuk / daftar mahasiswa</button></form>`;
 $('#register').addEventListener('change',e=>{$('#registration').hidden=!e.target.checked;});
 $('#login').onsubmit=e=>{e.preventDefault();const form=e.target,f=Object.fromEntries(new FormData(form));f.ctx=formContext(form);f.register=!!f.register;run(async()=>{await WA.login('student',f);mode='';await render();message('Akun mahasiswa tersimpan.');},form.querySelector('button'));};
}
function studentView(s){$('#main').innerHTML=`<h1>Absen mahasiswa</h1><section><b>${E(s.profile.account.nama)} · ${E(s.profile.account.nim)}</b><p class="small">${E(s.profile.account.ctx.prodi)} · semester ${E(s.profile.account.ctx.semester)} · kelas ${E(s.profile.account.ctx.kelas)}</p><p id="approval" role="status"></p><p class="help">1. Daftar dan tunggu persetujuan dosen. 2. Pindai QR dosen atau pilih file QR. 3. Pilih hadir/sakit/izin lalu kirim. Saat offline, tunjukkan QR balasan ke dosen sebelum waktu habis. Berhasil tercatat jika muncul ‘Absen diterima’.</p><button class="primary" id="scanSession">Pindai QR dosen</button><button id="enableNotices">Aktifkan pemberitahuan absen</button><div id="studentSession"></div></section><section><h2>Riwayat absen</h2><div id="history"></div></section>`;$('#enableNotices').onclick=()=>run(async()=>{if(window.Android?.requestNotifications){window.Android.requestNotifications();const s=await WA.get();window.Android.startWatch?.(s.token,s.profile.account.nim);message('Pengingat Android diaktifkan.');return;}if(!('Notification'in window))throw Error('Gunakan Chrome/Edge atau aplikasi Android untuk pemberitahuan.');const permission=await Notification.requestPermission();if(permission==='granted'){const reg=await navigator.serviceWorker.ready,key=await WA.api('push-key'),raw=Uint8Array.from(atob(key.publicKey.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0)),subscription=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:raw});await WA.api('push-subscribe',{subscription:subscription.toJSON()});message('Pemberitahuan diaktifkan, termasuk saat aplikasi browser ditutup.');}else message('Pemberitahuan belum diizinkan.');});$('#scanSession').onclick=()=>scan(async code=>{const read=await WA.readQR(code);if(!read.challenge)throw Error('Pindai QR sesi dari dosen.');challenge=read.challenge;studentDraft={code,challenge,mark:'.',reason:'',replyCode:''};studentSession();saveStudentDraft();await studentNotices(await WA.get());});}
function studentSession(){if(!challenge)return;$('#studentSession').innerHTML=`<h2>${E(challenge.matkul)}</h2><p>Pertemuan ${challenge.slot} · batas ${new Date(challenge.deadline).toLocaleTimeString('id-ID')}</p><form id="replyForm"><label>Keterangan<select name="mark"><option value=".">Hadir (.)</option><option value="S">Sakit (S)</option><option value="I">Izin (I)</option></select></label><label>Alasan sakit / izin<textarea name="reason" maxlength="500" placeholder="Isi bila sakit atau izin"></textarea></label><label><input type="checkbox" name="location"> Sertakan lokasi saat mengirim</label><p class="small">Bila dipilih, aplikasi meminta izin lokasi. Dosen dapat melihat koordinat, waktu, dan akurasinya untuk meninjau keterangan. Lokasi diambil sekali saat mengirim.</p><button class="primary">Kirim absen / buat QR balasan</button></form><button id="savedReply" type="button" hidden>Tampilkan QR balasan tersimpan</button>`;const form=$('#replyForm');form.elements.mark.value=studentDraft?.mark||'.';form.elements.reason.value=studentDraft?.reason||'';form.addEventListener('input',saveStudentDraft);form.addEventListener('change',saveStudentDraft);$('#savedReply').hidden=!studentDraft?.replyCode;$('#savedReply').onclick=()=>showCode(studentDraft.replyCode,'QR balasan mahasiswa');$('#replyForm').onsubmit=e=>{e.preventDefault();run(async()=>{const form=e.target;let location=null;if(form.elements.location.checked){if(!navigator.geolocation)throw Error('Lokasi belum tersedia pada perangkat.');location=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,at:p.timestamp}),()=>reject(Error('Izin lokasi belum diberikan. Anda dapat mencoba lagi atau mengirim tanpa lokasi.')),{enableHighAccuracy:true,timeout:15000,maximumAge:0}));}const code=await WA.reply(challenge,form.elements.mark.value,form.elements.reason.value,location);studentDraft={...studentDraft,replyCode:code};saveStudentDraft();$('#savedReply').hidden=false;if(navigator.onLine){try{const acceptedId=challenge.id;await WA.submitReply(code);window.Android?.attendanceAccepted?.(acceptedId);message('Absen diterima.');return;}catch(error){message(error.message+' Tunjukkan QR ke dosen sebelum batas waktu.');}}await showCode(code,'QR balasan mahasiswa');message('QR perlu dipindai dosen sebelum waktu absen habis. Membuat QR saja belum mencatat kehadiran.');},e.target.querySelector('button'));};}
async function studentNotices(s){
 if(mode!=='student'||!s.profile?.account||!document.getElementById('studentSession'))return;const time=WA.now(s);
 const recorded=x=>s.snapshot.marks.some(m=>m.scope===x.scope&&m.slot===x.slot&&m.nim===s.profile.account.nim&&!!m.mark);
 const active=s.snapshot.sessions.filter(x=>WA.sameCtx(x.ctx,s.profile.account.ctx)&&x.day===WA.day(time)&&x.deadline>time&&!recorded(x));
 if(!document.getElementById('activeSessions')){const box=document.createElement('div');box.id='activeSessions';document.getElementById('studentSession').before(box);}
 const activeKey=JSON.stringify(active.map(x=>[x.id,x.version,x.deadline]));if(activeKey!==noticesKey){noticesKey=activeKey;document.getElementById('activeSessions').innerHTML=active.map(x=>`<div class="card" data-active-session="${x.id}"><b>${E(x.matkul)} · pertemuan ${x.slot}</b><p>Absen sedang dibuka dosen.</p><b class="sessionClock" data-end="${x.deadline}"></b><p class="small">Pindai QR yang ditampilkan dosen sebelum waktu habis.</p></div>`).join('');}
 for(const x of s.snapshot.sessions.filter(recorded)){const key=s.profile.device+':'+x.id+':'+x.version;if(closedNotices.has(key))continue;window.Android?.attendanceAccepted?.(x.id);if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.getRegistration();if(reg)for(const n of await reg.getNotifications({tag:'wa-'+x.id}))n.close();}closedNotices.add(key);}
 for(const x of active){const remaining=x.deadline-time,phase=remaining<=60000?'reminder':'start',key='wa-notice-'+x.id+'-'+x.version+'-'+phase;if(localStorage.getItem(key))continue;localStorage.setItem(key,'1');const body=phase==='start'?`${x.matkul}: waktu absen dimulai. Pindai QR dosen.`:`Segera absen ${x.matkul}, waktu tersisa kurang dari 1 menit.`;message(body);if(window.Android?.notifySession)window.Android.notifySession(x.id,'Absen mahasiswa',body);else if(window.Android?.notify)window.Android.notify('Absen mahasiswa',body);else if('Notification'in window&&Notification.permission==='granted'){const reg=await navigator.serviceWorker.ready;await reg.showNotification('Absen mahasiswa',{body,tag:'wa-'+x.id,icon:'icon.svg'});}}
 if(challenge&&s.snapshot.sessions.some(x=>x.id===challenge.id&&recorded(x))){const acceptedId=challenge.id;challenge=null;studentDraft=null;if(draftKey)localStorage.removeItem(draftKey);document.getElementById('studentSession').innerHTML='<p class="present">Absen diterima. Hitung mundur dan pengingat sesi ini sudah dihentikan.</p>';window.Android?.attendanceAccepted?.(acceptedId);if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.getRegistration();if(reg)for(const n of await reg.getNotifications({tag:'wa-'+acceptedId}))n.close();}}
 clock();
}
async function render(){if(rendering)return;rendering=true;try{const s=await WA.get(),role=s.profile?.role||'login';clockOffset=WA.now(s)-Date.now();$('#connection').textContent=(navigator.onLine?'Online':'Offline')+(s.outbox.length?' · '+s.outbox.length+' perubahan':'');$('#sync').hidden=!s.profile;$('#logout').hidden=!s.profile;if(mode!==role){mode=role;resultsKey=historyKey=noticesKey='';if(role==='login')loginView();else if(role==='teacher'){$('#main').innerHTML='<p>Halaman ini khusus mahasiswa. Keluar dari akun dosen untuk masuk dengan NIM dan PIN mahasiswa.</p>';return;}else{draftKey='wa-student-draft-'+s.profile.device;studentDraft=JSON.parse(localStorage.getItem(draftKey)||'null');challenge=null;if(studentDraft?.code){try{challenge=(await WA.readQR(studentDraft.code)).challenge;}catch(_){studentDraft=null;localStorage.removeItem(draftKey);}}studentView(s);if(challenge)studentSession();}}if(role==='student'){await studentNotices(s);$('#approval').textContent=s.profile.account.approved?'Akun disetujui dosen.':'Pendaftaran sudah terkirim ke server. Menunggu dosen menyetujui di menu Persetujuan akun mahasiswa. Hasil diperbarui otomatis saat online.';$('#scanSession').disabled=!s.profile.account.approved;const hkey=JSON.stringify(s.snapshot.marks);if(historyKey!==hkey){historyKey=hkey;$('#history').innerHTML=s.snapshot.marks.filter(x=>x.mark).map(x=>`<p>${E(s.snapshot.sessions.find(session=>session.scope===x.scope)?.matkul||'Mata kuliah')} · pertemuan ${x.slot}: <b>${E(x.mark==='.'?'Hadir (.)':x.mark)}</b> · ${E(x.review_status==='pending'?'Menunggu tinjauan':x.review_status==='rejected'?'Tidak disetujui':'Tercatat')}</p>`).join('')||'<p class="small">Belum ada absen diterima.</p>';}}if(s.authExpired)message('Akses perangkat di server sudah berakhir. Sinkronisasi memerlukan login ulang.');}finally{rendering=false;}}
async function showCode(code,title,session=null){qrCode=code;qrSession=session;$('#codeTitle').textContent=title;const qr=qrcode(0,'M');qr.addData(code);qr.make();$('#codeImage').innerHTML=qr.createSvgTag({cellSize:4,margin:6,scalable:true});$('#codeDialog').showModal();clock();}
function clock(){const t=Date.now()+clockOffset;document.querySelectorAll('.sessionClock').forEach(x=>{const left=Math.max(0,Math.ceil((Number(x.dataset.end)-t)/1000));x.textContent=left?Math.floor(left/60)+':'+String(left%60).padStart(2,'0')+' tersisa':'Absen ditutup · A otomatis';});$('#countdown').textContent=qrSession?(qrSession.deadline>t?'Sisa '+Math.max(0,Math.ceil((qrSession.deadline-t)/60000))+' menit':'Batas absen sudah berakhir'):'';}
async function download(blob,name){if(window.Android?.saveFile){const reader=new FileReader();reader.onload=()=>window.Android.saveFile(name,blob.type,reader.result);reader.readAsDataURL(blob);return;}const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
async function scan(fn){scanHandler=fn;$('#scanner').showModal();try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});$('#camera').srcObject=stream;await $('#camera').play();const canvas=$('#scanCanvas'),video=$('#camera');async function tick(){if(!stream)return;if(video.readyState>=2){const scale=Math.min(1,640/video.videoWidth);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);const c=canvas.getContext('2d',{willReadFrequently:true});c.drawImage(video,0,0,canvas.width,canvas.height);const data=c.getImageData(0,0,canvas.width,canvas.height),result=jsQR(data.data,data.width,data.height,{inversionAttempts:'attemptBoth'});if(result&&await acceptScan(result.data))return;}frameTimer=setTimeout(tick,120);}tick();}catch(_){message('Kamera belum diizinkan. Pilih foto QR atau tempel kode.');}}
async function acceptScan(code){return await run(async()=>{await scanHandler(code);stopScan();return true;});}
function stopScan(){stream?.getTracks().forEach(t=>t.stop());stream=null;clearTimeout(frameTimer);$('#scanner').close();}
$('#stopScan').onclick=stopScan;$('#scanner').addEventListener('cancel',stopScan);$('#scanner').addEventListener('close',()=>{stream?.getTracks().forEach(t=>t.stop());stream=null;clearTimeout(frameTimer);});$('#readText').onclick=()=>acceptScan($('#qrText').value.trim());$('#qrImage').onchange=e=>run(async()=>{const file=e.target.files[0];e.target.value='';if(file)await acceptScan(await WAQRFiles.read(file));});$('#closeCode').onclick=()=>$('#codeDialog').close();$('#shareCode').onclick=()=>run(async()=>{const png=await WAQRFiles.png(qrCode),file=new File([png],'absensi-qr.png',{type:'image/png'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:$('#codeTitle').textContent});return;}await download(png,'absensi-qr.png');});$('#sync').onclick=()=>run(async()=>{await WA.sync();message(WA.lastError||'Sinkronisasi selesai.');});$('#logout').onclick=()=>run(async()=>{if(await WA.logout()){window.Android?.stopWatch?.();mode='';await render();}});WA.on(render);window.addEventListener('offline',render);window.addEventListener('online',render);navigator.serviceWorker?.addEventListener('message',e=>{if(e.data.type==='offline-progress'&&$('#offlineStatus'))$('#offlineStatus').textContent='Menyiapkan offline: '+e.data.done+'/'+e.data.total+' berkas';if(e.data.type==='offline-ready'&&$('#offlineStatus'))$('#offlineStatus').textContent='Siap offline: lembar dan pustaka konversi sudah tersimpan.';if(e.data.type==='offline-error')message('Penyiapan offline belum lengkap. Tekan Sinkronkan saat internet tersedia.');});setInterval(()=>{clock();if(mode==='student')WA.get().then(studentNotices);},1000);setInterval(()=>{if(!document.hidden)void WA.sync();},5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)void WA.sync();});window.WAFlush=async()=>saveStudentDraft();await render();if((await WA.get()).profile){void WA.prepareOffline();void WA.sync();}
})();
