/* Local records and outbox are committed together. No password or PIN is saved. */
(() => {
'use strict';
const ROOT=new URL('../',document.currentScript.src), enc=new TextEncoder(), dec=new TextDecoder();
const fresh=()=>({token:null,profile:null,snapshot:{roster:[],sessions:[],marks:[],documents:[],registrations:[]},outbox:[],selection:null});
let opening, syncing, dispatching, bootstrapping, syncAgain=false, documentWrite=Promise.resolve(); const inFlight=new Set(); const listeners=new Set(), channel=typeof BroadcastChannel==='function'?new BroadcastChannel('wa-records'):null;
function db(){return opening ||=new Promise((resolve,reject)=>{const r=indexedDB.open('web-absensi-offline',1);r.onupgradeneeded=()=>r.result.createObjectStore('records');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function get(key='state'){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction('records').objectStore('records').get(key);r.onsuccess=()=>resolve(r.result??(key==='state'?fresh():null));r.onerror=()=>reject(r.error);});}
async function change(fn,key='state'){const d=await db();return new Promise((resolve,reject)=>{const t=d.transaction('records','readwrite'),store=t.objectStore('records'),r=store.get(key);let result;r.onsuccess=()=>{try{result=fn(r.result??(key==='state'?fresh():null));store.put(result,key);}catch(e){reject(e);t.abort();}};t.oncomplete=()=>{if(key==='state')emit();resolve(result);};t.onerror=()=>reject(t.error);});}
function emit(){listeners.forEach(fn=>fn());channel?.postMessage('changed');window.dispatchEvent(new Event('wa-changed'));}channel?.addEventListener('message',()=>{listeners.forEach(fn=>fn());window.dispatchEvent(new Event('wa-changed'));});
const b64=bytes=>btoa(Array.from(new Uint8Array(bytes),v=>String.fromCharCode(v)).join('')).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');
const unb64=s=>Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));
const encode=obj=>b64(enc.encode(JSON.stringify(obj)));const decode=s=>JSON.parse(dec.decode(unb64(s)));
const ctx=c=>({jenjang:'S1',prodi:c.prodi,semester:String(c.semester),kelas:String(c.kelas).replace(/^Kelas /,'').toUpperCase()});
const sameCtx=(a,b)=>JSON.stringify(ctx(a))===JSON.stringify(ctx(b));
async function scope(c,course=''){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(JSON.stringify([ctx(c),course.trim()])))),v=>v.toString(16).padStart(2,'0')).join('');}
async function keys(){let value=await get('keys');if(!value){const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},false,['sign','verify']);value={privateKey:pair.privateKey,pub:b64(await crypto.subtle.exportKey('spki',pair.publicKey))};await change(old=>old||value,'keys');value=await get('keys');}return value;}
async function seal(data){const k=await keys(),body=encode(data),sig=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},k.privateKey,enc.encode(body));return body+'.'+b64(sig);}
async function open(envelope,pub){if(typeof envelope!=='string'||envelope.length>23000)throw Error('Kode QR tidak valid.');const [body,sig,extra]=envelope.split('.');if(extra||!body||!sig)throw Error('Kode QR tidak valid.');const key=await crypto.subtle.importKey('spki',unb64(pub),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);if(!await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,unb64(sig),enc.encode(body)))throw Error('Tanda tangan QR tidak cocok.');return decode(body);}
async function api(action,data={},token){const state=await get();const response=await fetch(new URL('app_api.php',ROOT),{method:'POST',headers:{'Content-Type':'application/json','X-App-Request':'1',...(token??state.token?{'Authorization':'Bearer '+(token??state.token)}:{})},body:JSON.stringify({action,...data}),credentials:'same-origin'});let result;try{result=await response.json();}catch(_){throw Error('Server belum dapat dihubungi. Periksa sambungan internet.');}if(!response.ok||result.status!=='success'){const error=Error(result.message||'Permintaan belum berhasil.');error.code=result.code;throw error;}return result;}
async function login(role,fields){if(!navigator.onLine)throw Error('Masuk pertama kali memerlukan internet.');const k=await keys();let result;if(role==='teacher'){const body=new URLSearchParams({action:'login_privat',username:fields.username,password:fields.password});const response=await fetch(new URL('index.php',ROOT),{method:'POST',body,credentials:'same-origin'});const content=await response.json();if(content.status!=='success')throw Error(content.message||content.msg||'Nama atau kata sandi tidak cocok.');result=await api('bootstrap',{pubkey:k.pub});}else result=await api(fields.register?'register':'student-login',{...fields,ctx:ctx(fields.ctx),pubkey:k.pub});result.snapshot.receivedAt=Date.now();await change(s=>({...fresh(),token:result.token,profile:result.snapshot.profile,snapshot:result.snapshot}));void prepareOffline();return result;}
async function bootstrap(){if(bootstrapping)return bootstrapping;return bootstrapping=(async()=>{const k=await keys(),result=await api('bootstrap',{pubkey:k.pub});result.snapshot.receivedAt=Date.now();await change(s=>({...s,token:result.token,profile:result.snapshot.profile,snapshot:result.snapshot}));return result;})().finally(()=>{bootstrapping=null;});}
function applyOp(s,o){const p=s.snapshot;
if(o.type==='session'){const i=p.sessions.findIndex(x=>x.id===o.session.id);if(i<0)p.sessions.push(o.session);else p.sessions[i]=o.session;if(o.session.deadline>now(s))p.marks=p.marks.filter(m=>!(m.scope===o.session.scope&&m.slot===o.session.slot&&m.source==='automatic'));}
if(o.type==='student-upsert'||o.type==='student-delete'){const i=p.roster.findIndex(x=>sameCtx(x,o.ctx)&&x.nim===o.nim);if(o.type==='student-delete'){if(i>=0)p.roster.splice(i,1);}else{const row={...ctx(o.ctx),nim:o.nim,nama:o.nama,jk:o.jk,id:i>=0?p.roster[i].id:o.id};if(i<0)p.roster.push(row);else p.roster[i]=row;}}
if(o.type==='mark'||o.type==='review'||(o.type==='reply'&&o.localMark)){const row=o.localMark||{scope:o.scope,slot:o.slot,nim:o.nim,mark:o.mark,reason:o.reason||'',source:'manual',review_status:o.review_status||'final',revision:o.baseRevision||0,recorded_at:Date.now()};const i=p.marks.findIndex(x=>x.scope===row.scope&&x.slot===row.slot&&x.nim===row.nim);if(i<0)p.marks.push(row);else p.marks[i]={...p.marks[i],...row};}
if(o.type==='document'){const row={scope:o.scope,kind:o.kind,ctx:o.ctx,matkul:o.matkul,content:o.content,revision:o.baseRevision||0};const i=p.documents.findIndex(x=>x.scope===o.scope&&x.kind===o.kind);if(i<0)p.documents.push(row);else p.documents[i]=row;}
}
async function queue(op){op={...op,id:op.id||crypto.randomUUID()};if(op.ctx)op.ctx=ctx(op.ctx);if(op.ctx&&op.matkul!==undefined)op.scope=await scope(op.ctx,op.matkul);await change(s=>{if(s.profile?.role!=='teacher')throw Error('Masuk dengan akun dosen.');if(!s.outbox.some(x=>x.id===op.id)){s.outbox.push(op);applyOp(s,op);}return s;});void sync();return op;}
function dispatchPush(s){if(s.profile?.role!=='teacher'||dispatching)return;dispatching=api('dispatch-push').catch(()=>{}).finally(()=>{dispatching=null;});}
async function sync(){window.WA.lastError='';if(syncing){syncAgain=true;return syncing;}syncAgain=false;syncing=(async()=>{const s=await get();if(!s.token||!navigator.onLine)return;try{const active=s.outbox.filter(o=>!o.problem).slice(0,100);active.forEach(o=>inFlight.add(o.id));const r=await api(active.length?'sync':'snapshot',active.length?{operations:active.slice(0,100)}:{knownTag:s.snapshot.tag||''});dispatchPush(s);if(r.unchanged){await change(current=>{current.snapshot.serverTime=r.serverTime;current.snapshot.receivedAt=Date.now();return current;});return;}await change(current=>{const results=new Map((r.results||[]).map(x=>[x.id,x]));current.outbox=current.outbox.filter(o=>results.get(o.id)?.status!=='success');for(const o of current.outbox){const result=results.get(o.id);if(result&&['conflict','error'].includes(result.status))o.problem=result;}r.snapshot.receivedAt=Date.now();current.snapshot=r.snapshot;current.profile=r.snapshot.profile;for(const o of current.outbox){const predecessor=active.find(a=>results.get(a.id)?.status==='success'&&a.type===o.type&&a.scope===o.scope&&(o.type==='document'?a.kind===o.kind:o.type==='mark'?a.nim===o.nim&&a.slot===o.slot:false));if(predecessor&&!results.has(o.id)&&!o.problem){const remote=o.type==='document'?r.snapshot.documents.find(x=>x.scope===o.scope&&x.kind===o.kind):r.snapshot.marks.find(x=>x.scope===o.scope&&x.nim===o.nim&&x.slot===o.slot);o.baseRevision=remote?.revision||0;}applyOp(current,o);}return current;});}catch(e){if(e.code==='AUTH_REQUIRED'){await change(s=>{s.authExpired=true;return s;});}window.WA.lastError=e.message;}finally{inFlight.clear();}})().finally(()=>{syncing=null;if(syncAgain){syncAgain=false;void sync();}});return syncing;}
async function resolve(id,keep){await change(s=>{const o=s.outbox.find(x=>x.id===id);if(!o)return s;if(keep){o.id=crypto.randomUUID();o.baseRevision=o.problem.revision??o.problem.remote?.revision??0;if(o.base&&o.problem.remote)o.base={nama:o.problem.remote.nama};delete o.problem;}else s.outbox=s.outbox.filter(x=>x.id!==id);return s;});await sync();}
function saveDocument(c,course,kind,content){const write=documentWrite.catch(()=>{}).then(async()=>{const sc=await scope(c,course);await change(s=>{if(s.profile?.role!=='teacher')throw Error('Masuk dengan akun dosen.');let o=s.outbox.find(o=>o.type==='document'&&o.scope===sc&&o.kind===kind&&!o.problem&&!inFlight.has(o.id));if(o)o.content=content;else{const old=s.snapshot.documents.find(x=>x.scope===sc&&x.kind===kind);o={id:crypto.randomUUID(),type:'document',ctx:ctx(c),matkul:course,scope:sc,kind,content,baseRevision:old?.revision||0};s.outbox.push(o);}applyOp(s,o);return s;});void sync();});documentWrite=write;return write;}

function now(s){return Date.now()+(s?.snapshot?.serverTime&&s?.snapshot?.receivedAt?s.snapshot.serverTime-s.snapshot.receivedAt:0);}
function day(t=Date.now()){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(t);}
async function startSession(c,course,slot,minutes){if(!course.trim())throw Error('Isi mata kuliah untuk sesi absen ini.');if(!Number.isFinite(minutes)||minutes<=0||minutes>1440)throw Error('Isi durasi antara 1 dan 1440 menit.');const s=await get(),sc=await scope(c,course),old=s.snapshot.sessions.find(x=>x.scope===sc&&x.slot===Number(slot)),t=now(s);if(old&&old.day!==day(t))throw Error('Pertemuan ini sudah digunakan. Pilih pertemuan berikutnya.');if(old&&old.teacher_id!==s.profile.device)throw Error('Reset dilakukan dari perangkat pembuat QR.');const deadline=t+minutes*60000;if(day(t)!==day(deadline))throw Error('Batas absen harus berakhir pada tanggal yang sama.');const data={v:1,type:'session',device:s.profile.device,id:old?.id||crypto.randomUUID(),ctx:ctx(c),matkul:course.trim(),slot:Number(slot),starts:t,deadline,ends:deadline,version:(old?.version||0)+1,nonce:b64(crypto.getRandomValues(new Uint8Array(24))).replaceAll('-','a').replaceAll('_','b')};data.nonce=Array.from(crypto.getRandomValues(new Uint8Array(24)),v=>v.toString(16).padStart(2,'0')).join('');const challenge=await seal(data),session={...data,scope:sc,day:day(t),challenge,teacher_id:s.profile.device,roster:s.snapshot.roster.filter(x=>sameCtx(x,c)).map(x=>x.nim)};await queue({type:'session',challenge,session});return session;}
function qr(type,certificate,field,envelope){return 'WA1:'+encode({type,certificate,[field]:envelope});}
async function readQR(code){if(!code?.startsWith('WA1:')||code.length>14000)throw Error('Gunakan QR dari aplikasi absensi.');const s=await get(),w=decode(code.slice(4)),identity=await open(w.certificate,s.profile.serverPublicKey);if(!identity.approved)throw Error('Pendaftaran mahasiswa belum disetujui.');if(w.type==='session'&&identity.role==='teacher'){const challenge=await open(w.challenge,identity.pub);if(challenge.device!==identity.device||challenge.type!=='session')throw Error('Kode sesi tidak cocok.');if(s.profile.role==='student'&&!sameCtx(challenge.ctx,s.profile.account.ctx))throw Error('QR ini berasal dari kelas lain.');return {identity,challenge,wrapper:w};}if(w.type==='reply'&&identity.role==='student'){const reply=await open(w.reply,identity.pub);if(reply.device!==identity.device||reply.type!=='reply')throw Error('Balasan tidak cocok.');return {identity,reply,wrapper:w};}throw Error('Jenis QR tidak cocok.');}
async function reply(challenge,mark,reason,location){const s=await get();if(!s.profile?.account.approved)throw Error('Menunggu persetujuan dosen.');if(day(now(s))!==day(challenge.starts)||now(s)<challenge.starts||now(s)>challenge.deadline)throw Error('Waktu absen sudah berakhir atau belum dimulai.');if(!['.','S','I'].includes(mark)||mark!=='.'&&!reason.trim())throw Error('Isi alasan sakit atau izin.');const envelope=await seal({v:1,type:'reply',device:s.profile.device,session:challenge.id,nonce:challenge.nonce,mark,reason:reason.trim(),location:location||null,at:now(s)});return qr('reply',s.profile.certificate,'reply',envelope);}
async function submitReply(code){const r=await api('sync',{operations:[{id:crypto.randomUUID(),type:'reply',code}]});const result=r.results[0];if(result.status!=='success')throw Error(result.message||'Absen belum diterima.');r.snapshot.receivedAt=Date.now();await change(s=>({...s,profile:r.snapshot.profile,snapshot:r.snapshot}));return result;}
async function receive(code){const s=await get(),{identity,reply:r}=await readQR(code),session=s.snapshot.sessions.find(x=>x.id===r.session),t=now(s);if(!session)throw Error('Sesi QR tidak ditemukan pada perangkat dosen.');const challenge=await open(session.challenge,s.profile.device===session.teacher_id?(await keys()).pub:session.teacher_pub);if(!['.','S','I'].includes(r.mark)||r.mark!=='.'&&!r.reason?.trim())throw Error('Keterangan mahasiswa tidak valid.');if(challenge.nonce!==r.nonce)throw Error('Kode sudah direset. Gunakan QR terbaru.');if(!sameCtx(identity.ctx,session.ctx)||!session.roster.includes(identity.nim))throw Error('Mahasiswa tidak terdaftar di kelas ini.');if(day(t)!==session.day||t<session.starts||t>session.deadline)throw Error('Batas waktu absen telah berakhir.');const old=s.snapshot.marks.find(x=>x.scope===session.scope&&x.slot===session.slot&&x.nim===identity.nim);if(old&&old.mark&&old.source!=='automatic')throw Error('Mahasiswa ini sudah tercatat '+old.mark+'.');const receipt=await seal({type:'receipt',device:s.profile.device,code,at:t});return queue({type:'reply',code,receipt,localMark:{scope:session.scope,slot:session.slot,nim:identity.nim,mark:r.mark,reason:r.reason,location:r.location,source:'qr-offline',review_status:r.mark==='.'?'final':'pending',recorded_at:t,session_id:session.id}});}
async function finalize(){await change(s=>{if(s.profile?.role!=='teacher')return s;for(const session of s.snapshot.sessions){if(session.starts>now(s)||session.deadline>now(s))continue;for(const nim of session.roster){const index=s.snapshot.marks.findIndex(x=>x.scope===session.scope&&x.slot===session.slot&&x.nim===nim);if(index>=0&&s.snapshot.marks[index].mark)continue;const mark={scope:session.scope,slot:session.slot,nim,mark:'A',reason:'Batas waktu absen telah berakhir.',source:'automatic',review_status:'final',revision:index>=0?s.snapshot.marks[index].revision:0,recorded_at:session.deadline,session_id:session.id};if(index>=0)s.snapshot.marks[index]=mark;else s.snapshot.marks.push(mark);}}return s;});}

async function logout(){const s=await get();if(s.outbox.length&&!confirm('Ada perubahan yang belum tersinkron. Keluar tetap menghapus salinan perangkat. Lanjutkan?'))return false;if(navigator.onLine){try{await api('logout');}catch(_){await change(()=>s.token,'revocation');}}else await change(()=>s.token,'revocation');const d=await db();await new Promise((resolve,reject)=>{const t=d.transaction('records','readwrite'),store=t.objectStore('records');store.delete('state');store.delete('keys');t.oncomplete=resolve;t.onerror=()=>reject(t.error);});for(const key of Object.keys(localStorage))if(/^(wa-|absen-|ujian_|custom_|absensi)/.test(key))localStorage.removeItem(key);const names=await caches.keys();await Promise.all(names.filter(x=>x.startsWith('wa-private')).map(x=>caches.delete(x)));emit();return true;}
async function prepareOffline(){if(!('serviceWorker'in navigator))return;const reg=await navigator.serviceWorker.register(new URL('app-sw.js',ROOT),{scope:ROOT.pathname});await navigator.serviceWorker.ready;const role=(await get()).profile?.role||new URLSearchParams(location.search).get('role')||'teacher';reg.active?.postMessage({type:'prepare',role,bundled:!!(window.Android||window.AbsensiDesktop)});if(navigator.storage?.persist)await navigator.storage.persist();}
window.WA={ROOT,get,change,ctx,sameCtx,scope,keys,seal,open,encode,decode,api,login,bootstrap,queue,sync,resolve,saveDocument,now,day,startSession,qr,readQR,reply,receive,submitReply,finalize,logout,prepareOffline,on:fn=>{listeners.add(fn);return()=>listeners.delete(fn);}};
window.addEventListener('online',async()=>{const revoke=await get('revocation');if(revoke){try{await api('logout',{},revoke);await change(()=>null,'revocation');}catch(_){}}void sync();});
})();
