/* Short contextual tours shared by the original teacher pages and student app. */
(()=>{
'use strict';
const script=document.currentScript,rootURL=new URL('./',script.src),student=/\/app\/(?:index\.html)?$/.test(location.pathname),page=student?'student':location.pathname.split('/').pop().replace(/\.php$/,'')||'index';
const get=k=>{try{return localStorage.getItem('wa-guide-'+k);}catch(_){return null;}},put=(k,v)=>{try{localStorage.setItem('wa-guide-'+k,String(v));}catch(_){}};
document.documentElement.dataset.waShowStatus=get('status')==='1'?'1':'0';
const step=(title,text,target,image,prepare)=>({title,text,target,image,prepare});
const qrOpen=()=>{if(document.querySelector('#attendanceQRPanel[hidden]'))document.getElementById('openAttendanceQR')?.click();};
const sidebar=()=>{const x=document.getElementById('sidebar');if(x&&!x.classList.contains('open')&&!x.classList.contains('active'))window.toggleSidebar?.();};
const chapters={
index:[['Masuk & pilih kelas',[step('Masuk sebagai dosen','Gunakan akun dosen. Mahasiswa masuk melalui Presen Go.','#authOverlay','teacher-login'),step('Pilih kelas','Pilih prodi, semester, dan kelas yang akan dikelola.','#prodi','home'),step('Buka data kelas','Tekan Masuk Sistem. Data dan lembar menggunakan kelas yang dipilih.','.main-card .btn-submit','home')]],['Persetujuan & cadangan',[step('Buka menu','Buka menu untuk persetujuan mahasiswa, sinkronisasi, dan cadangan.','#sidebar','qr',sidebar),step('Setujui mahasiswa','Cocokkan NIM dan kelas, lalu Setujui. Mahasiswa menekan Sinkronkan untuk melihat hasil.','#toolResults','qr',sidebar),step('Cadangkan data','Ekspor cadangan sebelum pindah perangkat. Simpan berkas dengan aman. Pulihkan hanya cadangan milik Anda.','#backup','roster',sidebar)]],['Tampilan & musik',[step('Pengaturan profil','Tekan profil untuk mengganti nama, foto, atau tema. Pengaturan tidak mengubah data absensi.','.user-profile-btn','home'),step('Musik latar','Gunakan tombol musik. Audio lokal tetap dapat diputar saat offline.','[onclick*="Musik"], [onclick*="Music"]','home')]]],
data_siswa:[['Daftar mahasiswa',[step('Tambah mahasiswa','Tekan Tambah, isi NIM lengkap, nama, dan L/P, lalu Simpan Data.','[onclick="bukaModalTambah()"]','roster'),step('Cari & koreksi','Cari NIM atau nama. Gunakan Edit pada baris yang tepat untuk memperbaiki data.','#searchInput','roster'),step('Buka lembar','Buka Lembar Absen atau Lembar Ujian dari kelas ini.','a[href^="absen.php"]','sheet')]],['Impor foto & dokumen',[step('Pilih berkas','Pilih foto, PDF, Word, atau Excel. Foto harus tajam dan memuat kolom NIM serta nama.','#fotoDaftarMahasiswa','roster'),step('Pilih area tabel','Jika foto miring, putar atau luruskan. Seret area tabel agar kop dan tanda tangan tidak ikut dibaca.','#ocrPreviewCanvas','roster'),step('Baca semua baris','Tekan Baca Semua Baris. Urutan mengikuti berkas asli; NIM tidak jelas ditandai untuk dikoreksi.','#btnOcrFoto','roster'),step('Periksa hasil','Cocokkan NIM, nama, dan urutan dengan gambar contoh per baris. Lengkapi kotak kosong dan L/P.','#ocrReviewRows','roster'),step('Simpan hasil','Simpan setelah seluruh identitas benar. Jangan mengisi NIM dengan perkiraan.','#btnSimpanOcr','roster')]]],
absen:[['Absensi QR',[step('Buka Absensi QR','Tekan Absensi QR pada lembar ini. Fitur berada di bawah menu lembar.','#openAttendanceQR','qr'),step('Atur sesi','Isi mata kuliah, nomor pertemuan, dan durasi. Nama mata kuliah ikut masuk ke lembar.','#sessionForm','qr',qrOpen),step('Bagikan QR','Tekan Mulai/Buat QR lalu Bagikan QR. Mahasiswa dapat membaca berkas gambar langsung.','#startSession','qr',qrOpen),step('Terima & setujui','Persetujuan akun dan pengajuan izin/sakit terlihat di panel ini. Saat offline, pindai QR balasan mahasiswa.','#toolResults','qr',qrOpen),step('Tanda kehadiran','Titik berarti hadir. S/I mengikuti pengajuan. A otomatis muncul setelah waktu QR habis, bukan saat masih berlangsung.','#tbodySiswa','sheet')]],['Edit & simpan lembar',[step('Isi identitas lembar','Tekan teks identitas untuk mengedit. Perubahan langsung disimpan di perangkat.','#metaLeftBox','sheet'),step('Isi kehadiran','Isi titik, S, I, atau A pada pertemuan yang tepat. Kembali atau tutup aplikasi tetap menyimpan perubahan.','#tbodySiswa','sheet'),step('Atur lembar','Gunakan pengaturan untuk ukuran, posisi, font, dan margin. Periksa pratinjau sebelum mencetak.','#inspectorToggleBtn','sheet'),step('Tanda tangan','Masukkan gambar tanda tangan pada kotak yang sesuai. Tanda tangan tidak menimpa tabel.','[data-signature-upload]','sheet')]],['Rekap, nilai & cetak',[step('Rekap nilai','Buka Rekap Nilai. Isi komponen nilai dan bobot, lalu simpan untuk lembar ujian.','#tourBtnRekap','sheet'),step('Baris & pertemuan','Tambah/hapus baris atau kolom hanya bila diperlukan. Hapus permanen menghapus data kelas dan meminta konfirmasi.','#tourBtnTambah','sheet'),step('Ekspor atau cetak','Gunakan Word, Excel, atau Cetak. Pilih ukuran kertas dan orientasi sebelum mencetak.','#tourBtnPrint','sheet')]]],
ujian:[['Lembar ujian',[step('Isi mata kuliah & jadwal','Tekan mata kuliah, ruang, dan waktu untuk mengisi identitas ujian. Kolom kosong dapat diisi sendiri.','[data-app-course]','sheet'),step('Nilai mahasiswa','Nilai berasal dari rekap lembar absen. Periksa kelas dan mata kuliah sebelum mencetak.','#examTableBlock','sheet'),step('Tanda tangan','Tambahkan gambar tanda tangan pengawas dan dosen pada kotak masing-masing.','[data-signature-upload]','sheet'),step('Format & keluaran','Atur font dan posisi lewat pengaturan. Ekspor Word/Excel atau Cetak setelah memeriksa lembar.','[onclick="cetakLembarUjian()"]','sheet')]]],
music_player:[['Pemutar musik',[step('Audio lokal','Pilih audio dari perangkat untuk digunakan saat offline.','#localMusicFile','home'),step('Cari audio','Isi judul atau artis lalu Cari audio. Pencarian memerlukan internet.','#searchForm','home'),step('Volume & latar','Atur volume. Tekan Tutup untuk kembali; musik dapat tetap berjalan di latar.','#volume','home')]]],
student:[['Masuk & persetujuan',[step('Masuk mahasiswa','Pilih kelas, isi NIM lengkap dan PIN. Gunakan data yang sama saat masuk kembali.','#login','student-login'),step('Daftar pertama kali','Jika belum terdaftar, pilih Daftar. Isi nama dan L/P dengan benar, lalu tunggu persetujuan dosen.','#register','student-login'),step('Periksa persetujuan','Tekan Sinkronkan saat online. Jika masih menunggu, minta dosen memeriksa daftar persetujuan kelas Anda.','#approval, #registration','student-login')]],['Isi absensi QR',[step('Pilih sesi atau pindai','Pilih sesi aktif atau Pindai QR dosen. Hanya sesi kelas Anda yang dapat digunakan.','#scanSession, #activeSessions','student-qr'),step('Baca berkas QR','Pilih foto QR menerima PNG/SVG asli; tidak perlu screenshot. Kamera memerlukan izin.','#qrImage','student-qr'),step('Isi kehadiran','Pilih Hadir, Sakit, atau Izin. Beri alasan untuk Sakit/Izin, lalu kirim sebelum waktu habis.','#replyForm','student-qr'),step('Jika offline','Tampilkan QR balasan dan serahkan kepada dosen untuk dipindai sebelum batas waktu. QR tersimpan dapat dibuka lagi.','#savedReply','student-qr'),step('Periksa hasil','Buka riwayat untuk melihat hasil dan status pengiriman. Sinkronkan saat internet kembali.','#history','student-qr')]],['Notifikasi & akun',[step('Pengingat sesi','Aktifkan notifikasi jika tersedia. Tetap periksa sesi aktif ketika aplikasi dibuka.','#enableNotices','student-qr'),step('Keluar akun','Keluar akun hanya untuk berganti pengguna. Pastikan pengiriman selesai; jangan keluar saat masih ada antrean.','#logout','student-login')]]]
};
const groups=[...(chapters[page]||chapters.index),['Offline & sinkronisasi',[step('Siapkan saat online','Masuk pertama kali saat online. Buka halaman yang akan dipakai agar tersedia ketika jaringan terputus.',student?'#connection':'#toolConnection',student?'student-login':'home'),step('Perubahan tersimpan','Perubahan disimpan di perangkat. Sambungkan internet lalu Sinkronkan; tunggu antrean kosong sebelum pindah perangkat.',student?'#sync':'#toolConnection',student?'student-qr':'qr'),step('Periksa jika belum terkirim','Status lengkap dapat ditampilkan lewat kotak di bawah. Dosen memeriksa konflik di menu sinkronisasi; jangan menimpa tanpa memeriksa salinan.',student?'#connection':'#toolResults',student?'student-qr':'qr')]]],host=document.createElement('div');host.className='wa-guide';host.innerHTML='<div class="wa-guide-target" hidden><span class="wa-guide-pointer">Tombol / area ini ↑</span></div><div class="wa-guide-dock"><button class="wa-guide-grip" aria-label="Geser posisi panduan" title="Seret untuk memindahkan">⋮</button><button class="wa-guide-open" aria-label="Buka panduan" title="Panduan penggunaan">?<span class="wa-guide-dot"></span></button><button class="wa-guide-hide" aria-label="Perkecil panduan" title="Perkecil">›</button></div><section class="wa-guide-panel" hidden aria-label="Panduan penggunaan"><div class="wa-guide-heading"><strong>Panduan singkat</strong><button class="wa-guide-close" aria-label="Tutup panduan">×</button></div><select aria-label="Pilih panduan"></select><h3></h3><img alt="Contoh tampilan tombol dan area yang dijelaskan"><p class="wa-guide-text"></p><div class="wa-guide-actions"><button class="wa-guide-prev">Kembali</button><span class="wa-guide-count"></span><button class="wa-guide-next">Lanjut</button></div><div class="wa-guide-status"><p class="wa-guide-sync" aria-live="polite"></p><label><input type="checkbox" class="wa-guide-status-toggle">Tampilkan status sinkronisasi</label><p>Ikon dapat diseret. Tekan › untuk memperkecil, lalu garis di tepi untuk membukanya.</p></div></section>';
document.body.append(host);const q=s=>host.querySelector(s),dock=q('.wa-guide-dock'),panel=q('.wa-guide-panel'),frame=q('.wa-guide-target'),select=q('select');let chapter=0,index=0,target=null,drag=false;
groups.forEach((g,i)=>select.add(new Option(g[0],i)));dock.classList.toggle('is-small',get('small')==='1');let fraction=Number(get('position')||.46);
function dockPosition(){dock.style.top=Math.max(12,Math.min(innerHeight-dock.offsetHeight-12,innerHeight*fraction))+'px';}dockPosition();
function close(){panel.hidden=true;frame.hidden=true;target=null;q('.wa-guide-open').setAttribute('aria-expanded','false');}
function position(){dockPosition();if(panel.hidden)return;const visible=target&&target.getClientRects().length&&getComputedStyle(target).visibility!=='hidden';frame.hidden=!visible;
const w=innerWidth,h=innerHeight,pw=panel.offsetWidth,ph=panel.offsetHeight,rect=visible?target.getBoundingClientRect():null;let top=Math.max(12,Math.min(h-ph-12,h*.15));if(rect){frame.style.cssText=`left:${Math.max(0,rect.left-3)}px;top:${Math.max(0,rect.top-3)}px;width:${Math.min(w,rect.width+6)}px;height:${Math.min(h,rect.height+6)}px`;if(rect.bottom+ph+30<h)top=rect.bottom+28;else if(rect.top-ph-12>12)top=rect.top-ph-12;else top=rect.top<h/2?Math.max(12,h-ph-12):12;}
panel.style.top=Math.max(12,Math.min(h-ph-12,top))+'px';panel.style.right='40px';if(rect&&rect.right<w-pw-50)panel.style.right='16px';}
function render(){const s=groups[chapter][1][index];s.prepare?.();q('h3').textContent=s.title;q('.wa-guide-text').textContent=s.text;q('img').src=new URL('guide-images/'+s.image+'.png',rootURL);q('.wa-guide-count').textContent=(index+1)+' / '+groups[chapter][1].length;q('.wa-guide-prev').disabled=index===0;q('.wa-guide-next').textContent=index===groups[chapter][1].length-1?'Selesai':'Lanjut';target=document.querySelector(s.target);if(target&&target.getClientRects().length)target.scrollIntoView({block:'nearest',behavior:'instant'});position();}
q('.wa-guide-open').onclick=()=>{if(drag)return;if(dock.classList.contains('is-small')){dock.classList.remove('is-small');put('small',0);dockPosition();return;}panel.hidden=!panel.hidden;if(panel.hidden)close();else{q('.wa-guide-open').setAttribute('aria-expanded','true');render();}};
q('.wa-guide-hide').onclick=()=>{close();dock.classList.add('is-small');put('small',1);};q('.wa-guide-close').onclick=close;select.onchange=()=>{chapter=Number(select.value);index=0;render();};q('.wa-guide-prev').onclick=()=>{index=Math.max(0,index-1);render();};q('.wa-guide-next').onclick=()=>{if(index===groups[chapter][1].length-1)close();else{index++;render();}};
const toggle=q('.wa-guide-status-toggle');toggle.checked=get('status')==='1';toggle.onchange=()=>{put('status',toggle.checked?'1':'0');document.documentElement.dataset.waShowStatus=toggle.checked?'1':'0';};
const grip=q('.wa-guide-grip');grip.onpointerdown=e=>{drag=true;grip.setPointerCapture(e.pointerId);};grip.onpointermove=e=>{if(!drag)return;fraction=e.clientY/innerHeight;dockPosition();};grip.onpointerup=()=>{drag=false;put('position',fraction);};grip.onpointercancel=()=>{drag=false;};
// Keep controls available in native top-layer dialogs without blocking the page.
const observer=new MutationObserver(records=>{if(records.every(record=>host.contains(record.target)))return;const dialog=Array.from(document.querySelectorAll('dialog[open]')).pop(),parent=dialog||document.body;if(host.parentElement!==parent)parent.append(host);if(!panel.hidden){target=document.querySelector(groups[chapter][1][index].target);position();}});observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['open','hidden']});
async function status(){let s;try{s=await window.WA?.get();}catch(_){}const pending=s?.outbox?.length||0;q('.wa-guide-dot').classList.toggle('pending',!navigator.onLine||pending>0);q('.wa-guide-sync').textContent=(navigator.onLine?'Online':'Offline')+' · '+pending+' perubahan menunggu sinkronisasi'+(s?.outbox?.some(x=>x.problem)?' · perlu diperiksa di menu':'');}
void status();window.WA?.on(()=>void status());window.addEventListener('online',status);window.addEventListener('offline',status);window.addEventListener('resize',position);window.addEventListener('scroll',position,true);document.addEventListener('keydown',e=>{if(e.key==='Escape')close();});q('img').onload=position;q('img').title='Tekan gambar untuk memperbesar';q('img').onclick=()=>{q('img').classList.toggle('is-zoomed');position();};
})();
