/* Local records and outbox are committed together. No password or PIN is saved. */
(() => {
'use strict';
const ROOT=new URL('../',document.currentScript.src), enc=new TextEncoder(), dec=new TextDecoder();
const fresh=()=>({token:null,profile:null,snapshot:{roster:[],sessions:[],marks:[],documents:[],registrations:[]},outbox:[],selection:null});
let opening, syncing, dispatching, bootstrapping, syncAgain=false, documentWrite=Promise.resolve(); const inFlight=new Set(); const listeners=new Set(), channel=typeof BroadcastChannel==='function'?new BroadcastChannel('wa-records'):null;
function db(){return opening ||=new Promise((resolve,reject)=>{const r=indexedDB.open('web-absensi-offline',1);r.onupgradeneeded=()=>r.result.createObjectStore('records');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function get(key='state'){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction('records').objectStore('records').get(key);r.onsuccess=()=>resolve(r.result??(key==='state'?fresh():null));r.onerror=()=>reject(r.error);});}
async function change(fn,key='state'){const d=await db();return new Promise((resolve,reject)=>{const t=d.transaction('records','readwrite'),store=t.objectStore('records'),r=store.get(key);let result;r.onsuccess=()=>{try{result=fn(r.result??(key==='state'?fresh():null));store.put(result,key);}catch(e){reject(e);t.abort();}};t.oncomplete=()=>{if(key==='state')emit();resolve(result);};t.onerror=()=>reject(t.error);});}
function emit(){listeners.forEach(fn=>fn());channel?.postMessage('changed');window.dispatchEvent(new Event('wa-changed'));}channel?.addEventListener('message',()=>{listeners.forEach(fn=>fn());window.dispatchEvent(new Event('wa-changed'));});
const b64=bytes=>btoa(Array.from(new Uint8Array(bytes),v=>String.fromCharCode(v)).join('')).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');
const unb64=s=>Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));
const encode=obj=>b64(enc.encode(JSON.stringify(obj)));const decode=s=>JSON.parse(dec.decode(unb64(s)));
const ctx=c=>({jenjang:'S1',prodi:c.prodi,semester:String(c.semester),kelas:String(c.kelas).replace(/^Kelas /,'').toUpperCase()});
const sameCtx=(a,b)=>JSON.stringify(ctx(a))===JSON.stringify(ctx(b));
async function scope(c,course=''){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(JSON.stringify([ctx(c),course.trim()])))),v=>v.toString(16).padStart(2,'0')).join('');}
async function keys(){let value=await get('keys');if(!value){const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},false,['sign','verify']);value={privateKey:pair.privateKey,pub:b64(await crypto.subtle.exportKey('spki',pair.publicKey))};await change(old=>old||value,'keys');value=await get('keys');}return value;}
async function seal(data){const k=await keys(),body=encode(data),sig=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},k.privateKey,enc.encode(body));return body+'.'+b64(sig);}
async function open(envelope,pub){if(typeof envelope!=='string'||envelope.length>23000)throw Error('Kode QR tidak valid.');const [body,sig,extra]=envelope.split('.');if(extra||!body||!sig)throw Error('Kode QR tidak valid.');const key=await crypto.subtle.importKey('spki',unb64(pub),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);if(!await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,unb64(sig),enc.encode(body)))throw Error('Tanda tangan QR tidak cocok.');return decode(body);}
async function api(action,data={},token){const state=await get();const response=await fetch(new URL('app_api.php',ROOT),{method:'POST',headers:{'Content-Type':'application/json','X-App-Request':'1',...(token??state.token?{'Authorization':'Bearer '+(token??state.token)}:{})},body:JSON.stringify({action,...data}),credentials:'same-origin'});let result;try{result=await response.json();}catch(_){throw Error('Server belum dapat dihubungi. Periksa sambungan internet.');}if(!response.ok||result.status!=='success'){const error=Error(result.message||'Permintaan belum berhasil.');error.code=result.code;throw error;}return result;}
async function login(role,fields){if(!navigator.onLine)throw Error('Masuk pertama kali memerlukan internet.');const k=await keys();let result;if(role==='teacher'){const body=new URLSearchParams({action:'login_privat',username:fields.username,password:fields.password});const response=await fetch(new URL('index.php',ROOT),{method:'POST',body,credentials:'same-origin'});const content=await response.json();if(content.status!=='success')throw Error(content.message||content.msg||'Nama atau kata sandi tidak cocok.');result=await api('bootstrap',{pubkey:k.pub});}else result=await api(fields.register?'register':'student-login',{...fields,ctx:ctx(fields.ctx),pubkey:k.pub});result.snapshot.receivedAt=Date.now();await change(s=>({...fresh(),token:result.token,profile:result.snapshot.profile,snapshot:result.snapshot}));void prepareOffline();return result;}
async function bootstrap(){if(bootstrapping)return bootstrapping;return bootstrapping=(async()=>{const k=await keys(),result=await api('bootstrap',{pubkey:k.pub});result.snapshot.receivedAt=Date.now();await change(s=>({...s,token:result.token,profile:result.snapshot.profile,snapshot:result.snapshot}));return result;})().finally(()=>{bootstrapping=null;});}
function applyOp(s,o){const p=s.snapshot;
if(o.type==='session'){const i=p.sessions.findIndex(x=>x.id===o.session.id);if(i<0)p.sessions.push(o.session);else p.sessions[i]=o.session;if(o.session.deadline>now(s))p.marks=p.marks.filter(m=>!(m.scope===o.session.scope&&m.slot===o.session.slot&&m.source==='automatic'));}
if(o.type==='student-upsert'||o.type==='student-delete'){const i=p.roster.findIndex(x=>sameCtx(x,o.ctx)&&x.nim===o.nim);if(o.type==='student-delete'){if(i>=0)p.roster.splice(i,1);}else{const row={...ctx(o.ctx),nim:o.nim,nama:o.nama,jk:o.jk,id:i>=0?p.roster[i].id:o.id};if(i<0)p.roster.push(row);else p.roster[i]=row;}}
if(o.type==='mark'||o.type==='review'||(o.type==='reply'&&o.localMark)){const row=o.localMark||{scope:o.scope,slot:o.slot,nim:o.nim,mark:o.mark,reason:o.reason||'',source:'manual',review_status:o.review_status||'final',revision:o.baseRevision||0,recorded_at:Date.now()};const i=p.marks.findIndex(x=>x.scope===row.scope&&x.slot===row.slot&&x.nim===row.nim);if(i<0)p.marks.push(row);else p.marks[i]={...p.marks[i],...row};}
if(o.type==='document'){const row={scope:o.scope,kind:o.kind,ctx:o.ctx,matkul:o.matkul,content:o.content,revision:o.baseRevision||0};const i=p.documents.findIndex(x=>x.scope===o.scope&&x.kind===o.kind);if(i<0)p.documents.push(row);else p.documents[i]=row;}
}
async function queue(op){op={...op,id:op.id||crypto.randomUUID()};if(op.ctx)op.ctx=ctx(op.ctx);if(op.ctx&&op.matkul!==undefined)op.scope=await scope(op.ctx,op.matkul);await change(s=>{if(s.profile?.role!=='teacher')throw Error('Masuk dengan akun dosen.');if(!s.outbox.some(x=>x.id===op.id)){s.outbox.push(op);applyOp(s,op);}return s;});void sync();return op;}
function dispatchPush(s){if(s.profile?.role!=='teacher'||dispatching)return;dispatching=api('dispatch-push').catch(()=>{}).finally(()=>{dispatching=null;});}
// Delete the selected roster and enqueue its operations in one durable transaction.
async function deleteStudents(c,students){const operations=students.map(student=>({id:student.deleteId||crypto.randomUUID(),type:'student-delete',ctx:ctx(c),nim:student.nim,base:{nama:student.nama}}));await change(s=>{if(s.profile?.role!=='teacher')throw Error('Masuk dengan akun dosen.');for(const op of operations){if(!s.outbox.some(o=>o.id===op.id))s.outbox.push(op);applyOp(s,op);}return s;});void sync();return operations;}
async function sync(){window.WA.lastError='';if(syncing){syncAgain=true;return syncing;}syncAgain=false;syncing=(async()=>{const s=await get();if(!s.token||!navigator.onLine)return;try{const active=s.outbox.filter(o=>!o.problem).slice(0,100);active.forEach(o=>inFlight.add(o.id));const r=await api(active.length?'sync':'snapshot',active.length?{operations:active.slice(0,100)}:{knownTag:s.snapshot.tag||''});dispatchPush(s);if(r.unchanged){await change(current=>{current.snapshot.serverTime=r.serverTime;current.snapshot.receivedAt=Date.now();return current;});return;}await change(current=>{const results=new Map((r.results||[]).map(x=>[x.id,x]));current.outbox=current.outbox.filter(o=>results.get(o.id)?.status!=='success');for(const o of current.outbox){const result=results.get(o.id);if(result&&['conflict','error'].includes(result.status))o.problem=result;}r.snapshot.receivedAt=Date.now();current.snapshot=r.snapshot;current.profile=r.snapshot.profile;for(const o of current.outbox){const predecessor=active.find(a=>results.get(a.id)?.status==='success'&&a.type===o.type&&a.scope===o.scope&&(o.type==='document'?a.kind===o.kind:o.type==='mark'?a.nim===o.nim&&a.slot===o.slot:false));if(predecessor&&!results.has(o.id)&&!o.problem){const remote=o.type==='document'?r.snapshot.documents.find(x=>x.scope===o.scope&&x.kind===o.kind):r.snapshot.marks.find(x=>x.scope===o.scope&&x.nim===o.nim&&x.slot===o.slot);o.baseRevision=remote?.revision||0;}applyOp(current,o);}return current;});}catch(e){if(e.code==='AUTH_REQUIRED'){await change(s=>{s.authExpired=true;return s;});}window.WA.lastError=e.message;}finally{inFlight.clear();}})().finally(()=>{syncing=null;if(syncAgain){syncAgain=false;void sync();}});return syncing;}
async function resolve(id,keep){await change(s=>{const o=s.outbox.find(x=>x.id===id);if(!o)return s;if(keep){o.id=crypto.randomUUID();o.baseRevision=o.problem.revision??o.problem.remote?.revision??0;if(o.base&&o.problem.remote)o.base={nama:o.problem.remote.nama};delete o.problem;}else s.outbox=s.outbox.filter(x=>x.id!==id);return s;});await sync();}
function saveDocument(c,course,kind,content){const write=documentWrite.catch(()=>{}).then(async()=>{const sc=await scope(c,course);await change(s=>{if(s.profile?.role!=='teacher')throw Error('Masuk dengan akun dosen.');let o=s.outbox.find(o=>o.type==='document'&&o.scope===sc&&o.kind===kind&&!o.problem&&!inFlight.has(o.id));if(o)o.content=content;else{const old=s.snapshot.documents.find(x=>x.scope===sc&&x.kind===kind);o={id:crypto.randomUUID(),type:'document',ctx:ctx(c),matkul:course,scope:sc,kind,content,baseRevision:old?.revision||0};s.outbox.push(o);}applyOp(s,o);return s;});void sync();});documentWrite=write;return write;}

function now(s){return Date.now()+(s?.snapshot?.serverTime&&s?.snapshot?.receivedAt?s.snapshot.serverTime-s.snapshot.receivedAt:0);}
function day(t=Date.now()){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(t);}
async function startSession(c,course,slot,minutes){if(!course.trim())throw Error('Isi mata kuliah untuk sesi absen ini.');if(!Number.isFinite(minutes)||minutes<=0||minutes>1440)throw Error('Isi durasi antara 1 dan 1440 menit.');const s=await get(),sc=await scope(c,course),old=s.snapshot.sessions.find(x=>x.scope===sc&&x.slot===Number(slot)),t=now(s);if(old&&old.day!==day(t))throw Error('Pertemuan ini sudah digunakan. Pilih pertemuan berikutnya.');if(old&&old.teacher_id!==s.profile.device)throw Error('Reset dilakukan dari perangkat pembuat QR.');const deadline=t+minutes*60000;if(day(t)!==day(deadline))throw Error('Batas absen harus berakhir pada tanggal yang sama.');const data={v:1,type:'session',device:s.profile.device,id:old?.id||crypto.randomUUID(),ctx:ctx(c),matkul:course.trim(),slot:Number(slot),starts:t,deadline,ends:deadline,version:(old?.version||0)+1,nonce:b64(crypto.getRandomValues(new Uint8Array(24))).replaceAll('-','a').replaceAll('_','b')};data.nonce=Array.from(crypto.getRandomValues(new Uint8Array(24)),v=>v.toString(16).padStart(2,'0')).join('');const challenge=await seal(data),session={...data,scope:sc,day:day(t),challenge,teacher_id:s.profile.device,roster:s.snapshot.roster.filter(x=>sameCtx(x,c)).map(x=>x.nim)};await queue({type:'session',challenge,session});return session;}
function qr(type,certificate,field,envelope){return 'WA1:'+encode({type,certificate,[field]:envelope});}
async function readQR(code){if(!code?.startsWith('WA1:')||code.length>14000)throw Error('Gunakan QR dari aplikasi absensi.');const s=await get(),w=decode(code.slice(4)),identity=await open(w.certificate,s.profile.serverPublicKey);if(!identity.approved)throw Error('Pendaftaran mahasiswa belum disetujui.');if(w.type==='session'&&identity.role==='teacher'){const challenge=await open(w.challenge,identity.pub);if(challenge.device!==identity.device||challenge.type!=='session')throw Error('Kode sesi tidak cocok.');if(s.profile.role==='student'&&!sameCtx(challenge.ctx,s.profile.account.ctx))throw Error('QR ini berasal dari kelas lain.');return {identity,challenge,wrapper:w};}if(w.type==='reply'&&identity.role==='student'){const reply=await open(w.reply,identity.pub);if(reply.device!==identity.device||reply.type!=='reply')throw Error('Balasan tidak cocok.');return {identity,reply,wrapper:w};}throw Error('Jenis QR tidak cocok.');}
async function reply(challenge,mark,reason,location){const s=await get();if(!s.profile?.account.approved)throw Error('Menunggu persetujuan dosen.');if(day(now(s))!==day(challenge.starts)||now(s)<challenge.starts||now(s)>challenge.deadline)throw Error('Waktu absen sudah berakhir atau belum dimulai.');if(!['.','S','I'].includes(mark)||mark!=='.'&&!reason.trim())throw Error('Isi alasan sakit atau izin.');const envelope=await seal({v:1,type:'reply',device:s.profile.device,session:challenge.id,nonce:challenge.nonce,mark,reason:reason.trim(),location:location||null,at:now(s)});return qr('reply',s.profile.certificate,'reply',envelope);}
async function submitReply(code){const r=await api('sync',{operations:[{id:crypto.randomUUID(),type:'reply',code}]});const result=r.results[0];if(result.status!=='success')throw Error(result.message||'Absen belum diterima.');r.snapshot.receivedAt=Date.now();await change(s=>({...s,profile:r.snapshot.profile,snapshot:r.snapshot}));return result;}
async function receive(code){const s=await get(),{identity,reply:r}=await readQR(code),session=s.snapshot.sessions.find(x=>x.id===r.session),t=now(s);if(!session)throw Error('Sesi QR tidak ditemukan pada perangkat dosen.');const challenge=await open(session.challenge,s.profile.device===session.teacher_id?(await keys()).pub:session.teacher_pub);if(!['.','S','I'].includes(r.mark)||r.mark!=='.'&&!r.reason?.trim())throw Error('Keterangan mahasiswa tidak valid.');if(challenge.nonce!==r.nonce)throw Error('Kode sudah direset. Gunakan QR terbaru.');if(!sameCtx(identity.ctx,session.ctx)||!session.roster.includes(identity.nim))throw Error('Mahasiswa tidak terdaftar di kelas ini.');if(day(t)!==session.day||t<session.starts||t>session.deadline)throw Error('Batas waktu absen telah berakhir.');const old=s.snapshot.marks.find(x=>x.scope===session.scope&&x.slot===session.slot&&x.nim===identity.nim);if(old&&old.mark&&old.source!=='automatic')throw Error('Mahasiswa ini sudah tercatat '+old.mark+'.');const receipt=await seal({type:'receipt',device:s.profile.device,code,at:t});return queue({type:'reply',code,receipt,localMark:{scope:session.scope,slot:session.slot,nim:identity.nim,mark:r.mark,reason:r.reason,location:r.location,source:'qr-offline',review_status:r.mark==='.'?'final':'pending',recorded_at:t,session_id:session.id}});}
async function finalize(){await change(s=>{if(s.profile?.role!=='teacher')return s;for(const session of s.snapshot.sessions){if(session.starts>now(s)||session.deadline>now(s))continue;for(const nim of session.roster){const index=s.snapshot.marks.findIndex(x=>x.scope===session.scope&&x.slot===session.slot&&x.nim===nim);if(index>=0&&s.snapshot.marks[index].mark)continue;const mark={scope:session.scope,slot:session.slot,nim,mark:'A',reason:'Batas waktu absen telah berakhir.',source:'automatic',review_status:'final',revision:index>=0?s.snapshot.marks[index].revision:0,recorded_at:session.deadline,session_id:session.id};if(index>=0)s.snapshot.marks[index]=mark;else s.snapshot.marks.push(mark);}}return s;});}

async function logout(){const s=await get();if(s.outbox.length&&!confirm('Ada perubahan yang belum tersinkron. Keluar tetap menghapus salinan perangkat. Lanjutkan?'))return false;if(navigator.onLine){try{await api('logout');}catch(_){await change(()=>s.token,'revocation');}}else await change(()=>s.token,'revocation');const d=await db();await new Promise((resolve,reject)=>{const t=d.transaction('records','readwrite'),store=t.objectStore('records');store.delete('state');store.delete('keys');t.oncomplete=resolve;t.onerror=()=>reject(t.error);});for(const key of Object.keys(localStorage))if(/^(wa-|absen-|ujian_|custom_|absensi)/.test(key))localStorage.removeItem(key);const names=await caches.keys();await Promise.all(names.filter(x=>x.startsWith('wa-private')).map(x=>caches.delete(x)));emit();return true;}
async function prepareOffline(){if(!('serviceWorker'in navigator))return;const reg=await navigator.serviceWorker.register(new URL('app-sw.js',ROOT),{scope:ROOT.pathname,updateViaCache:'none'});await navigator.serviceWorker.ready;const role=(await get()).profile?.role||new URLSearchParams(location.search).get('role')||'teacher';reg.active?.postMessage({type:'prepare',role,bundled:!!(window.Android||window.AbsensiDesktop)});if(navigator.storage?.persist)await navigator.storage.persist();}
window.WA={ROOT,get,change,ctx,sameCtx,scope,keys,seal,open,encode,decode,api,login,bootstrap,queue,deleteStudents,sync,resolve,saveDocument,now,day,startSession,qr,readQR,reply,receive,submitReply,finalize,logout,prepareOffline,on:fn=>{listeners.add(fn);return()=>listeners.delete(fn);}};
window.addEventListener('online',async()=>{const revoke=await get('revocation');if(revoke){try{await api('logout',{},revoke);await change(()=>null,'revocation');}catch(_){}}void sync();});
})();

;
/* Connect the existing sheets to the persistent device records. */
(async()=>{
'use strict';window.WASheetReady=false;if(!window.WA)return;const page=location.pathname.split('/').pop().replace('.php',''),params=new URLSearchParams(location.search);let state=await WA.get();
if(!state.profile&&navigator.onLine&&page!=='music_player'){try{await WA.bootstrap();state=await WA.get();void WA.prepareOffline();}catch(_){return;}}
if(!state.profile)return;if(state.profile.role!=='teacher'&&page!=='music_player'){location.replace(new URL('app/?role=student',WA.ROOT));return;}
const c=WA.ctx({prodi:params.get('prodi')||state.selection?.prodi||'Pendidikan Teknologi Informasi',semester:params.get('semester')||state.selection?.semester||'1',kelas:params.get('kelas')||state.selection?.kelas||'A'});let course=params.get('matkul')??(WA.sameCtx(c,state.selection||c)?state.selection?.matkul||'':'');let loading=false,redirecting=false,timer,gradeTimer,loadedKey='',loadedRoster='',loadedScope='',flushing=false,flushPromise=Promise.resolve(),deletePromise=Promise.resolve();const draftPrefix='wa-sheet-draft-'+state.profile.device+'-',deletePrefix='wa-delete-draft-'+state.profile.device+'-',pendingMarks={};
const nativeFetch=window.fetch.bind(window),kind=page==='absen'?'attendance-sheet':'exam-sheet';
function input(value,cls=''){const el=document.createElement('input');el.type='text';el.value=value;el.className=cls;if(cls==='attendance-cell'){el.maxLength=1;el.setAttribute('autocomplete','off');}return el;}
function text(value){const el=document.createElement('td');el.textContent=value;return el;}
function notify(message){window.showToast?.(message);if(!window.showToast){const b=document.getElementById('waStatus');if(b)b.textContent=message;}}
function contextURL(url){const u=new URL(url,location.href);if(u.origin===location.origin&&/\/(absen|ujian|data_siswa)\.php$/.test(u.pathname)){for(const[k,v]of Object.entries({...c,matkul:course}))u.searchParams.set(k,v);}return u;}
const bar=document.createElement('div');bar.id='waStatus';bar.textContent=navigator.onLine?'Data perangkat siap · online':'Data perangkat siap · offline';bar.style.cssText='position:fixed;bottom:4px;left:50%;transform:translateX(-50%);background:#12354e;color:white;font:11px system-ui;padding:4px 10px;border-radius:8px;z-index:9990;pointer-events:none';document.body.append(bar);const style=document.createElement('style');style.textContent='[data-wa-hydrating] #paperSheet,[data-wa-hydrating] #paper{pointer-events:none;opacity:.7}@media print{#waStatus{display:none!important}}';document.head.append(style);
function roster(s){return s.snapshot.roster.filter(r=>WA.sameCtx(r,c)).sort((a,b)=>Number(a.id)-Number(b.id));}
function captureAttendance(){const table=document.getElementById('tabelAbsen');if(!table)return null;return {head:Array.from(table.tHead.rows).map(row=>Array.from(row.cells).map(cell=>({text:cell.textContent,colspan:cell.colSpan,rowspan:cell.rowSpan,id:cell.id,cls:cell.className}))),rows:Array.from(table.tBodies[0].rows).filter(row=>!row.classList.contains('page-preview-only')).map(row=>Array.from(row.cells).map(cell=>cell.querySelector('input')?.value??cell.textContent))};}
function restoreAttendance(data,students){if(!Array.isArray(data?.head)||!Array.isArray(data.rows)||data.rows.length>5000)return;const table=document.getElementById('tabelAbsen');table.tHead.textContent='';for(const cells of data.head.slice(0,3)){const row=document.createElement('tr');for(const value of cells.slice(0,30)){const cell=document.createElement('th');cell.textContent=String(value.text??'');cell.colSpan=Math.max(1,Math.min(24,Number(value.colspan)||1));cell.rowSpan=Math.max(1,Math.min(3,Number(value.rowspan)||1));if(['headerPertemuan','thLabelId'].includes(value.id))cell.id=value.id;cell.contentEditable='true';if(['date-entry','meeting-number'].includes(value.cls))cell.className=value.cls;row.append(cell);}table.tHead.append(row);}if(table.tHead.rows[1])table.tHead.rows[1].id='subHeaderPertemuan';if(table.tHead.rows[2])table.tHead.rows[2].id='numberHeaderPertemuan';const body=table.tBodies[0];body.textContent='';for(const saved of data.rows){if(!Array.isArray(saved)||saved.length<6)continue;const values=saved.slice(),nim=String(values[1]||'').trim().toUpperCase(),student=students.find(s=>s.nim.toUpperCase()===nim);if(nim&&!student)continue;if(student){values[1]=student.nim;values[2]=student.nama;values[3]=student.jk;}const row=document.createElement('tr');row.dataset.nim=String(values[1]||'');values.slice(0,30).forEach((value,i)=>{const cell=text('');if(i===0){cell.className='row-no';cell.textContent=body.rows.length+1;}else{cell.append(input(String(value??''),i>=4&&i<values.length-1?'attendance-cell':i===1?'nim-input':i===2?'name-input':''));}row.append(cell);});body.append(row);}}
async function hydrate(initial=false){if(loading||flushing||localStorage.getItem(draftPrefix+encodeURIComponent(JSON.stringify([c,course,kind]))))return;state=await WA.get();if(!state.profile){if(page!=='index'&&!redirecting){redirecting=true;location.replace(new URL('index.php',WA.ROOT));}return;}const sc=await WA.scope(c,course),students=roster(state),marks=state.snapshot.marks.filter(m=>m.scope===sc),doc=state.snapshot.documents.find(d=>d.scope===sc&&d.kind===kind);loadedScope=sc;const gradesDoc=state.snapshot.documents.find(d=>d.scope===sc&&d.kind==='grade'),rosterKey=JSON.stringify(students),rosterChanged=rosterKey!==loadedRoster;const newKey=JSON.stringify([sc,students,marks,doc,gradesDoc]);bar.textContent=(navigator.onLine?'Online':'Offline')+` · ${state.outbox.length} perubahan belum tersinkron`;if(!initial&&newKey===loadedKey)return;loadedKey=newKey;loadedRoster=rosterKey;loading=true;try{
if(page==='absen'){
const tbody=document.getElementById('tbodySiswa');if(initial&&tbody){tbody.querySelectorAll('tr:not(.page-preview-only)').forEach(r=>r.remove());for(const [i,s]of students.entries()){const row=document.createElement('tr');row.className='student-row';row.dataset.nim=s.nim;const no=text(i+1);no.className='row-no';row.append(no);for(const [val,cls]of [[s.nim,'nim-input'],[s.nama,'name-input'],[s.jk,'']]){const cell=text('');cell.append(input(val,cls));row.append(cell);}const count=Number(document.getElementById('headerPertemuan')?.colSpan||16);for(let slot=1;slot<=count;slot++){const cell=text('');const el=input(marks.find(m=>m.nim===s.nim&&m.slot===slot)?.mark||'','attendance-cell');el.setAttribute('aria-label',`${s.nama} pertemuan ${slot}`);cell.append(el);row.append(cell);}const ket=text('');ket.append(input(doc?.content?.ket?.[s.nim]||''));row.append(ket);tbody.append(row);}}
if(initial&&doc?.content?.table)restoreAttendance(doc.content.table,students);
if(tbody&&rosterChanged){for(const row of tbody.querySelectorAll('tr:not(.page-preview-only)')){const nim=(row.dataset.nim||row.cells[1]?.querySelector('input')?.value||'').trim().toUpperCase();if(!nim)continue;const student=students.find(s=>s.nim.toUpperCase()===nim);if(!student){row.remove();continue;}[student.nim,student.nama,student.jk].forEach((value,i)=>{const el=row.cells[i+1]?.querySelector('input');if(el&&document.activeElement!==el)el.value=value;});}}
if(tbody){for(const student of students){if(Array.from(tbody.rows).some(r=>r.cells[1]?.querySelector('input')?.value===student.nim))continue;const row=document.createElement('tr');row.className='student-row';row.dataset.nim=student.nim;row.append(text(tbody.rows.length+1));for(const[v,cls]of [[student.nim,'nim-input'],[student.nama,'name-input'],[student.jk,'']]){const cell=text('');cell.append(input(v,cls));row.append(cell);}for(let slot=1;slot<=Number(document.getElementById('headerPertemuan')?.colSpan||16);slot++){const cell=text('');cell.append(input('','attendance-cell'));row.append(cell);}const ket=text('');ket.append(input(''));row.append(ket);tbody.append(row);}}
if(tbody){for(const r of tbody.querySelectorAll('tr:not(.page-preview-only)')){const nim=r.cells[1]?.querySelector('input')?.value;Array.from(r.querySelectorAll('.attendance-cell')).forEach((el,i)=>{if(document.activeElement!==el)el.value=marks.find(m=>m.nim===nim&&m.slot===i+1)?.mark||'';});}}
if(tbody)Array.from(tbody.querySelectorAll('tr:not(.page-preview-only)')).forEach((row,i)=>{const no=row.querySelector('.row-no')||row.cells[0];if(no)no.textContent=i+1;});
if(rosterChanged){const recap=document.getElementById('tbodyRekapNilai');if(recap){for(const row of Array.from(recap.rows)){const nim=row.querySelector('.nim-value')?.textContent,student=students.find(s=>s.nim===nim);if(!student)row.remove();else if(row.cells[1])row.cells[1].textContent=student.nama;}Array.from(recap.rows).forEach((r,i)=>r.cells[0].textContent=i+1);}}
const left=document.querySelectorAll('#metaLeftBox .meta-val');if(left[0])left[0].textContent=`Semester ${c.semester} (${Number(c.semester)%2?'Ganjil':'Genap'})`;if(left[2])left[2].textContent=c.prodi;const right=document.querySelectorAll('#metaRightBox .meta-val');if(right[2])right[2].textContent='Kelas '+c.kelas;
}
if(page==='ujian'&&(initial||rosterChanged)){const body=document.querySelector('#examTableBlock tbody'),grades=state.snapshot.documents.find(d=>d.scope===sc&&d.kind==='grade')?.content?.data_nilai||[];if(body){body.textContent='';for(const[i,s]of students.entries()){const g=grades.find(g=>g.nim===s.nim)||{},row=document.createElement('tr');for(const value of[i+1,s.nim,s.nama,g.skor_akhir??'',g.nilai_huruf??'',g.angka_mutu??'',''])row.append(text(value));row.cells[2].className='name';row.cells[6].contentEditable='true';row.cells[6].dataset.editKey='ket-'+encodeURIComponent(s.nim);body.append(row);}}const semester=document.querySelector('[data-edit-key="semester-label"]');if(semester)semester.textContent=`${c.semester} ${c.kelas} (${Number(c.semester)%2?'Ganjil':'Genap'})`;const prodi=document.querySelector('[data-edit-key="prodi-label"]');if(prodi)prodi.textContent=c.prodi;const count=document.querySelector('#examMetaRight .meta-row:nth-child(3) .meta-value');if(count)count.textContent=students.length;}
if(page==='data_siswa'&&(initial||rosterChanged)){const tbody=document.querySelector('#tabelSiswa tbody');if(tbody){tbody.textContent='';for(const[i,s]of students.entries()){const row=document.createElement('tr');row.className='student-row';row.dataset.nim=s.nim;for(const val of[i+1,s.nim,s.nama,s.jk])row.append(text(val));const cell=text(''),edit=document.createElement('button'),remove=document.createElement('button');edit.textContent='Edit';remove.textContent='Hapus';edit.type=remove.type='button';edit.className='btn-custom btn-primary';remove.className='btn-custom btn-danger';edit.onclick=()=>window.bukaModalEdit?.(s.id,s.nim,s.nama,s.jk);remove.onclick=async()=>{if(confirm('Hapus mahasiswa '+s.nama+'?')){await deleteStudents([s]);}};cell.append(edit,remove);row.append(cell);tbody.append(row);}if(!students.length){const row=document.createElement('tr'),cell=text('Belum ada data mahasiswa untuk prodi, semester, dan kelas ini.');cell.colSpan=5;cell.style.cssText='text-align:center;color:var(--text-muted);padding:30px';row.append(cell);tbody.append(row);}}}
if(initial&&doc?.content){const content=doc.content;for(const[slot,src]of Object.entries(content.signatures||{})){if(!/^data:image\/(png|jpeg|webp);base64,/.test(src))continue;const el=document.querySelector(`[data-signature-slot="${CSS.escape(slot)}"]`),img=el?.querySelector('.sheet-signature-image');if(img){img.src=src;img.hidden=false;el.classList.add('has-signature');el.querySelector('[data-signature-upload]').textContent='Ganti gambar';el.querySelector('[data-signature-remove]').hidden=false;}}for(const [selector,value]of Object.entries(content.text||{})){try{const el=document.querySelector(selector);if(el)el.textContent=value;}catch(_){}}for(const [key,value]of Object.entries(content.storage||{})){try{localStorage.setItem(key,value);}catch(_){}}}
const removeSelect=document.querySelector('[name=hapus_permanen_id]');if(removeSelect&&(initial||rosterChanged)){const selected=removeSelect.value;removeSelect.replaceChildren(new Option('-- Pilih Mahasiswa Satuan --',''));for(const student of students)removeSelect.add(new Option(student.nim+' - '+student.nama,student.nim));removeSelect.value=students.some(s=>s.nim===selected)?selected:'';}
const field=document.querySelector('[data-app-course]');if(initial&&field){field.textContent=course;field.oninput=()=>{course=field.textContent.trim();const url=new URL(location.href);url.searchParams.set('matkul',course);history.replaceState(null,'',url);void WA.change(s=>({...s,selection:{...c,matkul:course}}));};}fitNIM();
if(initial){document.querySelectorAll('a[href]').forEach(a=>{const u=contextURL(a.href);if(u.origin===location.origin)a.href=u.href;});if(page==='ujian')window.readSavedEdits?.();if(page==='absen')window.muatPosisiAbsen?.();}
window.pastikanJarakTandaTangan?.();if(page==='absen')window.perbaruiPenandaHalaman?.();if(page==='ujian')window.perbaruiPenandaHalamanUjian?.();
bar.textContent=(navigator.onLine?'Online':'Offline')+` · ${state.outbox.length} perubahan belum tersinkron`;
}finally{loading=false;}}
function fitNIM(){const head=document.getElementById('thLabelId');if(!head)return;const probe=document.createElement('canvas').getContext('2d');let width=120;document.querySelectorAll('#tbodySiswa tr:not(.page-preview-only) td:nth-child(2) input').forEach(el=>{probe.font=getComputedStyle(el).font;width=Math.max(width,Math.ceil(probe.measureText(el.value).width)+24);el.title=el.value;});head.style.width=head.style.minWidth=width+'px';}
function captureContent(){const values={},storage={},ket={},signatures={};document.querySelectorAll('[data-signature-slot]').forEach(slot=>{const img=slot.querySelector('.sheet-signature-image');if(img&&!img.hidden&&/^data:image\/(png|jpeg|webp);base64,/.test(img.src))signatures[slot.dataset.signatureSlot]=img.src;});document.querySelectorAll('[data-edit-key],.meta-val,[contenteditable="true"][id]').forEach(el=>{let selector=el.dataset.editKey?`[data-edit-key="${CSS.escape(el.dataset.editKey)}"]`:el.id?'#'+CSS.escape(el.id):null;if(!selector){const parent=el.parentElement?.parentElement;if(parent?.id)selector='#'+parent.id+' .meta-row:nth-child('+(Array.from(parent.children).indexOf(el.parentElement)+1)+') .meta-val';}if(selector)values[selector]=el.textContent;});for(const key of Object.keys(localStorage))if(/^(absen-layout|ujian_)/.test(key))storage[key]=localStorage.getItem(key);document.querySelectorAll('#tbodySiswa tr:not(.page-preview-only)').forEach(r=>{const nim=r.cells[1]?.querySelector('input')?.value;if(nim)ket[nim]=r.cells[r.cells.length-1]?.querySelector('input')?.value||'';});return {text:values,storage,ket,signatures,...(page==='absen'?{table:captureAttendance()}:{})};}
function stash(){if(loading||!['absen','ujian'].includes(page))return;const key=draftPrefix+encodeURIComponent(JSON.stringify([c,course,kind]));const previous=JSON.parse(localStorage.getItem(key)||'null');const draft={ctx:c,course,kind,content:captureContent(),marks:{...(previous?.marks||{}),...pendingMarks},at:Date.now()};localStorage.setItem(key,JSON.stringify(draft));for(const key of Object.keys(pendingMarks))delete pendingMarks[key];bar.textContent='Perubahan tersimpan di perangkat · menyiapkan sinkronisasi';}
function flush(){clearTimeout(timer);const task=flushPromise.catch(()=>{}).then(async()=>{flushing=true;try{for(const key of Object.keys(localStorage).filter(k=>k.startsWith(draftPrefix))){const raw=localStorage.getItem(key);if(!raw)continue;const draft=JSON.parse(raw);for(const mark of Object.values(draft.marks||{})){await WA.queue({type:'mark',ctx:draft.ctx,matkul:draft.course,...mark});}await WA.saveDocument(draft.ctx,draft.course,draft.kind,draft.content);if(localStorage.getItem(key)===raw)localStorage.removeItem(key);}for(const key of Object.keys(localStorage).filter(k=>k.startsWith(deletePrefix))){const raw=localStorage.getItem(key);if(!raw)continue;const intent=JSON.parse(raw);await WA.deleteStudents(intent.ctx,intent.students);if(localStorage.getItem(key)===raw)localStorage.removeItem(key);}}finally{flushing=false;}await hydrate();});flushPromise=task;return task;}
async function save(){try{stash();await flush();}catch(e){notify('Perubahan tetap disimpan di perangkat. '+e.message);}}
window.WAFlush=async()=>{await deletePromise;await flush();};
// Persist the intent before the first await: a closed renderer must not cancel deletion.
function deleteStudents(select){const students=(typeof select==='function'?select(roster(state)):select).map(s=>({nim:s.nim,nama:s.nama,deleteId:crypto.randomUUID()}));try{localStorage.setItem(deletePrefix+crypto.randomUUID(),JSON.stringify({ctx:c,students}));}catch(error){return Promise.reject(error);}const task=deletePromise.catch(()=>{}).then(async()=>{await flush();window.tutupModalHapusPermanen?.();notify(students.length?'Data mahasiswa dihapus pada perangkat. Penghapusan disinkronkan saat online.':'Daftar mahasiswa kelas ini sudah kosong.');});deletePromise=task;return task;}
document.addEventListener('submit',e=>{const form=e.target;if(!form.matches('form')||!form.querySelector('[name=aksi_hapus_permanen],[name=aksi_hapus_massal_kelas]'))return;e.preventDefault();e.stopImmediatePropagation();const single=form.querySelector('[name=hapus_permanen_id]'),nim=single?.value;if(single&&!nim){notify('Pilih mahasiswa yang akan dihapus.');return;}if(!confirm(single?'Hapus permanen mahasiswa '+nim+' dari kelas ini?':'Hapus semua mahasiswa kelas ini?'))return;void deleteStudents(rows=>rows.filter(row=>!single||row.nim===nim)).catch(err=>notify(err.message));},true);
document.addEventListener('click',e=>{if(page!=='data_siswa')return;const link=e.target.closest('a[href]');if(!link)return;const url=new URL(link.href);if(url.origin!==location.origin||!url.pathname.endsWith('/data_siswa.php')||!url.searchParams.has('hapus_semua')&&!url.searchParams.has('hapus_id'))return;e.preventDefault();e.stopImmediatePropagation();if(!confirm(url.searchParams.has('hapus_semua')?'Hapus semua mahasiswa kelas ini?':'Hapus mahasiswa ini?'))return;void deleteStudents(rows=>rows.filter(row=>url.searchParams.has('hapus_semua')||String(row.id)===url.searchParams.get('hapus_id'))).catch(err=>notify(err.message));},true);
window.WASetSheetCourse=async name=>{await flush();course=name.trim();const url=new URL(location.href);url.searchParams.set('matkul',course);history.replaceState(null,'',url);await WA.change(s=>({...s,selection:{...c,matkul:course}}));await hydrate(true);const field=document.querySelector('[data-app-course]');if(field)field.textContent=course;stash();await flush();};
document.addEventListener('input',e=>{if(loading)return;const el=e.target;if(!el.closest('#paperSheet,#paper,#tbodyRekapNilai')&&!el.id?.startsWith('bobot'))return;if(el.matches('#tbodySiswa .attendance-cell')){const row=el.closest('tr'),nim=row.cells[1]?.querySelector('input')?.value,slot=Array.from(row.querySelectorAll('.attendance-cell')).indexOf(el)+1,mark=el.value.trim().toUpperCase();if(nim&&['','.','A','S','I'].includes(mark)){const old=state.snapshot.marks.find(m=>m.scope===loadedScope&&m.nim===nim&&m.slot===slot);pendingMarks[nim+':'+slot]={id:crypto.randomUUID(),nim,slot,mark,baseRevision:old?.revision||0};}}stash();clearTimeout(timer);timer=setTimeout(()=>void flush().catch(e=>notify(e.message)),250);fitNIM();if(el.closest('#tbodyRekapNilai')||el.id?.startsWith('bobot')){clearTimeout(gradeTimer);gradeTimer=setTimeout(async()=>{const values={};document.querySelectorAll('#tbodyRekapNilai tr').forEach(row=>{values[row.querySelector('.nim-value')?.textContent]=Array.from(row.querySelectorAll('.score-input')).map(x=>x.value);});await WA.saveDocument(c,course,'grade',{...(state.snapshot.documents.find(d=>d.kind==='grade'&&WA.sameCtx(d.ctx,c)&&d.matkul===course)?.content||{}),draft:values});},250);}});
document.addEventListener('click',async e=>{const button=e.target.closest('button');if(button&&['absen','ujian'].includes(page)&&!button.closest('.teacher-tools,.wa-guide')){clearTimeout(timer);timer=setTimeout(save,0);}if(page==='absen'&&button?.textContent.includes('Rekap Nilai'))setTimeout(async()=>{const s=await WA.get(),sc=await WA.scope(c,course),draft=s.snapshot.documents.find(d=>d.scope===sc&&d.kind==='grade')?.content?.draft||{};document.querySelectorAll('#tbodyRekapNilai tr').forEach(row=>{const nim=row.querySelector('.nim-value')?.textContent;if(draft[nim])row.querySelectorAll('.score-input').forEach((el,i)=>{el.value=draft[nim][i]||'0';el.dispatchEvent(new Event('input',{bubbles:true}));});});},0);});
document.addEventListener('change',async e=>{const row=e.target.closest('#tbodySiswa tr');if(!row||e.target.classList.contains('attendance-cell'))return;const nim=row.cells[1]?.querySelector('input')?.value.trim().toUpperCase(),nama=row.cells[2]?.querySelector('input')?.value.trim(),jk=row.cells[3]?.querySelector('input')?.value.trim().toUpperCase();if(!nim||!nama||!['L','P'].includes(jk))return;const s=await WA.get(),old=s.snapshot.roster.find(x=>WA.sameCtx(x,c)&&x.nim===(row.dataset.nim||nim));if(row.dataset.nim&&!old){await hydrate();notify('Mahasiswa ini sudah dihapus dari daftar.');return;}if(old&&old.nim===nim&&old.nama===nama&&old.jk===jk)return;if(old&&old.nim!==nim)await WA.queue({type:'student-delete',ctx:c,nim:old.nim,base:{nama:old.nama}});row.dataset.nim=nim;await WA.queue({type:'student-upsert',ctx:c,nim,nama,jk,...(old?.nim===nim?{base:{nama:old.nama}}:{})});});
document.addEventListener('submit',async e=>{if(page!=='data_siswa'||!e.target.querySelector('[name="nim"]'))return;e.preventDefault();const values=Object.fromEntries(new FormData(e.target)),s=await WA.get(),old=s.snapshot.roster.find(x=>String(x.id)===values.id&&WA.sameCtx(x,c));try{if(old&&old.nim!==values.nim.toUpperCase())await WA.queue({type:'student-delete',ctx:c,nim:old.nim,base:{nama:old.nama}});await WA.queue({type:'student-upsert',ctx:c,nim:values.nim.trim().toUpperCase(),nama:values.nama,jk:values.jk,...(old?.nim===values.nim?{base:{nama:old.nama}}:{})});window.tutupModal?.();await hydrate(true);notify('Data disimpan di perangkat.');}catch(err){notify(err.message);}},true);
window.fetch=async(resource,init={})=>{const u=new URL(typeof resource==='string'?resource:resource.url||String(resource),location.href);if(page==='index'&&u.origin===location.origin&&u.pathname.endsWith('/index.php')&&init.body instanceof FormData){const body=init.body;if(body.get('action')==='logout_system'){await WA.logout();return new Response(JSON.stringify({status:'success'}),{headers:{'Content-Type':'application/json'}});}if(body.get('set_theme_session')){await WA.change(()=>body.get('theme_name'),'theme');if(navigator.onLine)return nativeFetch(resource,init);return new Response(JSON.stringify({status:'success'}),{headers:{'Content-Type':'application/json'}});}if(body.get('action')==='update_profile'){const profile={nama:body.get('admin_name'),role:body.get('admin_role'),avatar:body.get('admin_avatar')};await WA.change(()=>profile,'appearance-profile');if(navigator.onLine){try{return await nativeFetch(resource,init);}catch(_){}}return new Response(JSON.stringify({status:'success',msg:'Pengaturan tersimpan pada perangkat ini.'}),{headers:{'Content-Type':'application/json'}});}if(body.get('get_login_logs')){if(navigator.onLine){try{return await nativeFetch(resource,init);}catch(_){}}return new Response('[]',{headers:{'Content-Type':'application/json'}});}}if(u.origin===location.origin&&u.pathname.endsWith('/ujian.php')&&u.searchParams.get('aksi')==='simpan_nilai'){const payload=JSON.parse(init.body),sc=await WA.scope(c,course),s=await WA.get(),old=s.snapshot.documents.find(d=>d.scope===sc&&d.kind==='grade')?.content||{};await WA.saveDocument(c,course,'grade',{...old,...payload,prodi:c.prodi,semester:c.semester,kelas:c.kelas});return new Response(JSON.stringify({status:'success',jumlah:payload.data_nilai.length,saved_at:'Tersimpan pada perangkat'}),{headers:{'Content-Type':'application/json'}});}if(u.origin===location.origin&&u.pathname.endsWith('/data_siswa.php')&&u.searchParams.get('aksi')==='import_siswa'){const payload=init.body instanceof FormData?{rows:JSON.parse(init.body.get('rows')||'[]')}:JSON.parse(init.body),rows=payload.rows||payload.siswa||payload.data||[];let imported=0;for(const row of rows){await WA.queue({type:'student-upsert',ctx:c,nim:row.nim,nama:row.nama,jk:row.jk});imported++;}return new Response(JSON.stringify({status:'success',inserted:imported,imported,diimpor:imported,jumlah:imported,skipped:0,msg:'Data disimpan di perangkat.'}),{headers:{'Content-Type':'application/json'}});}return nativeFetch(resource,init);};
if(params.get('app')==='1'){const root=WA.ROOT.href;document.addEventListener('click',e=>{const a=e.target.closest('a');if(a&&a.href.startsWith(root)&&/\.php(?:\?|$)/.test(a.href)&&!a.download){const u=contextURL(a.href);u.searchParams.set('app','1');a.href=u.href;}});}
document.addEventListener('sheet-signature-changed',()=>{stash();void flush();});WA.on(()=>void hydrate());await flush();document.documentElement.dataset.waHydrating='1';await hydrate(true);delete document.documentElement.dataset.waHydrating;window.WASheetReady=true;if(page==='index'){const profile=await WA.get('appearance-profile'),theme=await WA.get('theme');if(theme)document.documentElement.dataset.theme=theme;for(const id of ['currentUserNameText','widgetAdminName']){const el=document.getElementById(id);if(el)el.textContent=profile?.nama||state.profile.account.nama;}for(const id of ['widgetAvatarImg','topNavAvatarImg','previewAvatarImg']){const el=document.getElementById(id);if(el&&/^data:image\/(png|jpeg|webp);base64,/.test(profile?.avatar||''))el.src=profile.avatar;}}void WA.sync();setInterval(()=>void WA.sync(),10000);window.addEventListener('pagehide',()=>{void flush();});document.addEventListener('visibilitychange',()=>{if(document.hidden)void flush();});document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a||a.download||a.target==='_blank'||e.ctrlKey||e.metaKey)return;const url=contextURL(a.href);if(url.origin!==location.origin||!url.pathname.endsWith('.php'))return;e.preventDefault();void window.WAFlush().then(()=>location.assign(url.href)).catch(err=>notify('Belum dapat berpindah: '+err.message));},true);
})();

;
/* QR and device tools belong to the original teacher pages, never a second dashboard. */
(async () => {
  'use strict';
  const host = document.getElementById('teacherTools');
  if (!host || !window.WA) return;
  const $ = selector => host.querySelector(selector);
  const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const sheet = host.dataset.page === 'absen', params = new URLSearchParams(location.search);
  let sessionQR = null, sessionCode = '', stream = null, scanTimer, renderKey = '', rendering = false;
  const notify = text => { $('#toolNotice').textContent = text; if(host.hidden) window.showToast?.(escape(text),'error'); };
  async function run(fn, button) {
    if (button) button.disabled = true;
    try { return await fn(); } catch (error) { notify(error.message); }
    finally { if (button) button.disabled = false; }
  }
  function context(state) {
    return WA.ctx(sheet ? Object.fromEntries(params) : {
      jenjang: document.getElementById('jenjang')?.value,
      prodi: document.getElementById('prodi')?.value,
      semester: document.getElementById('semester')?.value,
      kelas: document.getElementById('kelas')?.value,
      ...(!document.getElementById('prodi') ? state.selection : {})
    });
  }
  const course = () => $('#sessionForm')?.elements.matkul.value.trim() || '';
  async function download(blob, name) {
    if (window.Android?.saveFile) {
      const reader = new FileReader();
      reader.onload = () => Android.saveFile(name, blob.type, reader.result);
      reader.readAsDataURL(blob); return;
    }
    const url = URL.createObjectURL(blob), link = document.createElement('a');
    link.href = url; link.download = name; link.click();
    setTimeout(() => URL.revokeObjectURL(url), 60000);
  }
  async function showQR(session) {
    const state = await WA.get();
    if (session.teacher_id !== state.profile.device) throw Error('Tampilkan QR dari perangkat pembuat sesi.');
    sessionQR = session;
    const qr = qrcode(0, 'M');
    sessionCode=WA.qr('session', state.profile.certificate, 'challenge', session.challenge);qr.addData(sessionCode); qr.make();
    $('#codeTitle').textContent = session.matkul + ' · pertemuan ' + session.slot;
    $('#codeImage').innerHTML = qr.createSvgTag({cellSize:4, margin:6, scalable:true});
    $('#codeDialog').showModal(); clock();
  }
  function stopScan() {
    stream?.getTracks().forEach(track => track.stop()); stream = null; clearTimeout(scanTimer);
    if ($('#scanner')?.open) $('#scanner').close();
  }
  async function receive(code) {
    await WA.receive(code); stopScan(); notify('Absen diterima di Lembar Absen. Akan tersinkron saat online.');
  }
  async function startScan() {
    $('#scanner').showModal();
    try {
      stream = await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}, audio:false});
      const video = $('#camera'), canvas = $('#scanCanvas'); video.srcObject = stream; await video.play();
      const tick = async () => {
        if (!stream) return;
        if (video.readyState >= 2) {
          const scale = Math.min(1, 640/video.videoWidth);
          canvas.width = Math.round(video.videoWidth*scale); canvas.height = Math.round(video.videoHeight*scale);
          const ctx = canvas.getContext('2d', {willReadFrequently:true}); ctx.drawImage(video,0,0,canvas.width,canvas.height);
          const pixels = ctx.getImageData(0,0,canvas.width,canvas.height);
          const qr = jsQR(pixels.data,pixels.width,pixels.height,{inversionAttempts:'attemptBoth'});
          if (qr) { try { await receive(qr.data); return; } catch (error) { notify(error.message); } }
        }
        scanTimer = setTimeout(tick,150);
      }; void tick();
    } catch (_) { notify('Izinkan kamera, atau pilih foto QR / tempel kode.'); }
  }
  function clock() {
    void WA.get().then(state => {
      const now = WA.now(state);
      host.querySelectorAll('[data-end]').forEach(el => {
        const left = Math.max(0,Math.ceil((Number(el.dataset.end)-now)/1000));
        el.textContent = left ? Math.floor(left/60)+':'+String(left%60).padStart(2,'0')+' tersisa' : 'Absen ditutup · A otomatis';
      });
      if ($('#countdown')) $('#countdown').textContent = sessionQR ? Math.max(0,Math.ceil((sessionQR.deadline-now)/1000))+' detik tersisa' : '';
    });
  }
  function initialize(state) {
    host.hidden = false;
    const body = sheet ? `<form id="sessionForm"><label>Mata kuliah<input name="matkul" maxlength="180" required></label><div class="tool-grid"><label>Pertemuan<input name="slot" type="number" min="1" max="16" value="1" required></label><label>Durasi (menit)<input name="minutes" type="number" min="1" max="1440" placeholder="Misalnya 10" required></label></div><p>QR berlaku untuk kelas pada lembar ini. 1. Cocokkan kelas dan mata kuliah. 2. Isi pertemuan dan durasi. 3. Mulai lalu bagikan QR. Kolom tetap kosong selama waktu berjalan; A otomatis muncul sesudah tenggat. Untuk mahasiswa offline, pindai QR balasannya sebelum tenggat.</p><button id="startSession" type="submit">Mulai Absen / reset QR</button><button id="scanReply" type="button">Pindai QR mahasiswa</button><div id="sessionList"></div></form>` : '';
    $('#toolBody').innerHTML = body + '<div id="toolResults"></div>' + (!sheet ? `<details><summary>Cadangan perangkat</summary><button id="backup" type="button">Simpan cadangan</button><label>Pulihkan cadangan JSON<input id="restore" type="file" accept="application/json,.json"></label><p>Sinkronkan data pada aplikasi lama sebelum beralih. Cadangan tidak menyertakan akses login atau kunci QR.</p></details>` : '');
    if (sheet) {
      const form = $('#sessionForm');
      form.elements.matkul.value = params.get('matkul') || '';
      form.elements.slot.value = state.selection?.slot || 1;
      if(params.get('qrMinutes')) form.elements.minutes.value=params.get('qrMinutes');
      const draftKey='wa-qr-settings-'+state.profile.device+'-'+encodeURIComponent(JSON.stringify(context(state))),draft=JSON.parse(localStorage.getItem(draftKey)||'null');if(draft){form.elements.slot.value=draft.slot||1;form.elements.minutes.value=draft.minutes||'';}form.oninput=()=>localStorage.setItem(draftKey,JSON.stringify(Object.fromEntries(new FormData(form))));form.onchange = () => { renderKey = ''; void render(); };
      form.onsubmit = event => {
        event.preventDefault();
        void run(async () => {
          if (!window.WASheetReady) throw Error('Tunggu data lembar selesai dimuat.');
          const s = await WA.get(), c = context(s), values = Object.fromEntries(new FormData(form));
          const name = values.matkul.trim();
          const displayed = document.querySelector('[data-app-course]');
          if(displayed && displayed.textContent.trim()!==name) await window.WASetSheetCourse(name);
          await window.WAFlush?.();
          const session = await WA.startSession(c,name,Number(values.slot),Number(values.minutes));
          await showQR(session); notify('Absen dimulai. Kehadiran dicatat pada tabel asli di lembar ini.');
        }, $('#startSession'));
      };
      $('#scanReply').onclick = () => void startScan();
      $('#stopScan').onclick = stopScan;
      $('#scanner').addEventListener('close',stopScan);
      $('#readText').onclick = () => void run(() => receive($('#qrText').value.trim()));
      $('#qrImage').onchange = event => void run(async () => {const file=event.target.files[0];event.target.value='';if(file)await receive(await WAQRFiles.read(file));});
      $('#closeCode').onclick = () => $('#codeDialog').close();
      $('#shareCode').onclick = () => void run(async () => {
        const png=await WAQRFiles.png(sessionCode), file=new File([png],'absensi-qr.png',{type:'image/png'});
        if (navigator.canShare?.({files:[file]})) await navigator.share({files:[file],title:$('#codeTitle').textContent});
        else await download(png,'absensi-qr.png');
      });
    } else {
      $('#backup').onclick = () => void run(async () => download(new Blob([JSON.stringify({type:'web-absensi-backup',version:1,snapshot:(await WA.get()).snapshot},null,2)],{type:'application/json'}),'absensi-cadangan-'+WA.day()+'.json'));
      $('#restore').onchange = event => void run(async () => {
        const file=event.target.files[0]; if (!file || file.size>20000000) throw Error('Pilih cadangan JSON di bawah 20 MB.');
        const data=JSON.parse(await file.text()); if(data.type!=='web-absensi-backup'||!Array.isArray(data.snapshot?.roster)) throw Error('Berkas bukan cadangan absensi.');
        const s=await WA.get();
        if(s.snapshot.roster.length||s.snapshot.documents.length||s.snapshot.marks.length) throw Error('Data sudah terisi. Sinkronkan perangkat lama; pemulihan otomatis tidak dilakukan agar data yang ada tidak tertimpa.');
        if((data.snapshot.marks||[]).some(mark=>!(data.snapshot.sessions||[]).some(session=>session.scope===mark.scope))) throw Error('Cadangan memiliki absen tanpa konteks sesi. Gunakan sinkronisasi perangkat lama agar tidak ada catatan yang terlewat.');
        if(!confirm('Pulihkan cadangan pada perangkat kosong ini?')) return;
        for(const row of data.snapshot.roster) await WA.queue({type:'student-upsert',ctx:row,nim:row.nim,nama:row.nama,jk:row.jk});
        for(const doc of data.snapshot.documents||[]) await WA.saveDocument(doc.ctx,doc.matkul,doc.kind,doc.content);
        for(const mark of data.snapshot.marks||[]) {const session=data.snapshot.sessions.find(x=>x.scope===mark.scope); await WA.queue({type:'mark',ctx:session.ctx,matkul:session.matkul,slot:mark.slot,nim:mark.nim,mark:mark.mark,reason:mark.reason,baseRevision:0});}
        notify('Cadangan masuk ke antrean sinkronisasi.');
      });
      document.querySelector('.main-card form').addEventListener('change',()=>{renderKey='';void render();});
    }
    $('#sync').onclick = () => void run(async()=>{await WA.sync();notify(WA.lastError||'Sinkronisasi selesai.');});
  }
  async function render() {
    if(rendering) return; rendering=true;
    try {
      const state=await WA.get();
      if(state.profile?.role!=='teacher'){host.hidden=true;return;}
      if(!$('#toolResults')) initialize(state);
      $('#toolConnection').textContent=(navigator.onLine?'Online':'Offline')+' · '+state.outbox.length+' perubahan belum tersinkron';
      const c=context(state), scope=sheet?await WA.scope(c,course()):null;
      const key=JSON.stringify([scope,state.snapshot.roster,state.snapshot.sessions,state.snapshot.marks,state.snapshot.registrations,state.outbox]); if(key===renderKey) return; renderKey=key;
      const sessions=state.snapshot.sessions.filter(x=>x.scope===scope), marks=state.snapshot.marks.filter(x=>x.scope===scope);
      if(sheet) {
        $('#sessionList').innerHTML=sessions.map(x=>`<div class="tool-card">Pertemuan ${x.slot} · ${escape(x.day)} <b data-end="${x.deadline}"></b><button type="button" data-session="${x.id}">Tampilkan QR</button></div>`).join('');
        host.querySelectorAll('[data-session]').forEach(button=>button.onclick=()=>void run(()=>showQR(sessions.find(x=>x.id===button.dataset.session))));
      }
      const registrations=state.snapshot.registrations.filter(x=>!x.approved), pending=marks.filter(x=>['S','I'].includes(x.mark));
      $('#toolResults').innerHTML=(`<details open><summary>Persetujuan akun mahasiswa (${registrations.length})</summary>${registrations.map(x=>{const match=state.snapshot.roster.find(r=>WA.sameCtx(r,x.ctx)&&r.nim===x.nim);return `<div class="tool-card"><b>${escape(x.nama)} · ${escape(x.nim)}</b><p>${escape(x.ctx.prodi)} · semester ${escape(x.ctx.semester)} · kelas ${escape(x.ctx.kelas)}</p><p>${match?'Nama pada daftar: '+escape(match.nama):'NIM belum ada pada daftar. Persetujuan menambahkan mahasiswa ini.'}</p><button type="button" data-approve="${x.id}">Setujui setelah dicocokkan</button></div>`;}).join('')||'<p>Belum ada pendaftaran menunggu.</p>'}</details>`+(sheet?`<details><summary>Keterangan sakit & izin (${pending.length})</summary>${pending.map(x=>`<div class="tool-card"><b>${escape(x.nim)} · ${x.mark} · pertemuan ${x.slot}</b><p>${escape(x.reason)}</p><p>${x.location?`Lokasi: ${x.location.lat.toFixed(5)}, ${x.location.lon.toFixed(5)} · akurasi ±${Math.round(x.location.accuracy)} m`:'Lokasi tidak disertakan.'}</p><span>Status: ${escape(x.review_status)}</span><button type="button" data-review="${escape(x.nim)}:${x.slot}" data-status="accepted">Tandai sudah ditinjau</button><button type="button" data-review="${escape(x.nim)}:${x.slot}" data-status="rejected">Ubah menjadi A</button></div>`).join('')||'<p>Belum ada keterangan S/I.</p>'}</details>`:''))+`<details><summary>Perubahan belum tersinkron (${state.outbox.length})</summary>${state.outbox.filter(x=>x.problem).map(x=>`<div class="tool-card"><p>${escape(x.problem.message||'Ada perubahan pada perangkat lain.')}</p><button type="button" data-resolve="${x.id}" data-keep="1">Kirim salinan perangkat ini</button><button type="button" data-resolve="${x.id}" data-keep="0">Gunakan data server</button></div>`).join('')||'<p>Perubahan tersimpan di perangkat sampai server menerima sinkronisasi.</p>'}</details>`;
      host.querySelectorAll('[data-approve]').forEach(button=>button.onclick=()=>void run(async()=>{const op=await WA.queue({type:'approve',account:button.dataset.approve});await WA.sync();const current=await WA.get(),pending=current.outbox.find(x=>x.id===op.id);notify(pending?pending.problem?.message||'Persetujuan tersimpan di perangkat. Sambungkan internet lalu tekan Sinkronkan.':'Akun disetujui. Mahasiswa akan menerima hasil saat tersambung internet.');},button));
      host.querySelectorAll('[data-review]').forEach(button=>button.onclick=()=>void run(async()=>{const[nim,slot]=button.dataset.review.split(':'),mark=marks.find(x=>x.nim===nim&&x.slot===Number(slot)); await WA.queue({type:'review',ctx:c,matkul:course(),nim,slot:Number(slot),mark:button.dataset.status==='rejected'?'A':mark.mark,reason:mark.reason,review_status:button.dataset.status,baseRevision:mark.revision});},button));
      host.querySelectorAll('[data-resolve]').forEach(button=>button.onclick=()=>void run(()=>WA.resolve(button.dataset.resolve,button.dataset.keep==='1'),button));
      clock();
    } finally {rendering=false;}
  }
  if(!sheet) {
    window.WATeacher={prepare:async()=>{await WA.bootstrap();void WA.prepareOffline();}};
    const originalOnload=window.onload;
    window.onload=async event=>{
      const state=await WA.get();
      window.SERVER_CONFIG.isLoggedIn=state.profile?.role==='teacher'||window.SERVER_CONFIG.isLoggedIn;
      originalOnload?.call(window,event);
    };
    const state=await WA.get();
    if(state.profile?.role==='teacher') {
      window.SERVER_CONFIG.isLoggedIn=true;
      document.getElementById('authOverlay').style.display='none';
    }
  } else {
    document.getElementById('openAttendanceQR').onclick=()=>{
      if(!$('#toolResults')){notify('Tunggu data lembar selesai dimuat, lalu coba lagi.');return;}
      const displayed=document.querySelector('[data-app-course]');
      if(displayed) $('#sessionForm').elements.matkul.value=displayed.textContent.trim();
      renderKey='';void render();document.body.classList.add('wa-qr-open');document.getElementById('attendanceQRPanel').hidden=false;document.getElementById('attendanceQRPanel').scrollIntoView({behavior:'smooth',block:'start'});document.getElementById('openAttendanceQR').setAttribute('aria-expanded','true');
    };
    document.getElementById('closeAttendanceQR').onclick=()=>{document.body.classList.remove('wa-qr-open');document.getElementById('attendanceQRPanel').hidden=true;document.getElementById('openAttendanceQR').setAttribute('aria-expanded','false');};
  }
  let state=await WA.get();
  if(!state.profile&&navigator.onLine) {try {await WA.bootstrap();state=await WA.get();} catch (_) {}}
  if(!sheet&&state.profile?.role==='teacher') {window.SERVER_CONFIG.isLoggedIn=true;document.getElementById('authOverlay').style.display='none';}
  WA.on(()=>void render());window.addEventListener('online',()=>void render());window.addEventListener('offline',()=>void render());
  await render();
  if(state.profile?.role==='teacher') {void WA.prepareOffline();void WA.sync();}
  setInterval(()=>{clock();void WA.get().then(state=>{
    if(state.profile?.role==='teacher'&&state.snapshot.sessions.some(session=>session.deadline<=WA.now(state)&&session.roster.some(nim=>!state.snapshot.marks.some(mark=>mark.scope===session.scope&&mark.slot===session.slot&&mark.nim===nim&&!!mark.mark)))) void WA.finalize();
  });},1000);
  setInterval(()=>void WA.sync(),5000);
  if(sheet&&params.get('qr')==='1') document.getElementById('openAttendanceQR').click();
})();
